/*SERVER*/
export const SERVER_LINK = "http://localhost:8080";
//http://book.koyomiku39.moe:8080
/*PATH*/
export const LOGIN_PATH = "/login";
export const REGISTER_PATH = "/register";
export const HOME_PATH = "/";
export const PROFILE_PATH = "/me";
export const BOOK_PATH = "/book";
export const CART_PATH = "/cart";
export const SKILL_BOOK_PATH = "";
export const BUSINESS_BOOK_PATH = "";
export const LITERATURE_BOOK_PATH = "";
export const KIDS_BOOK_PATH = "";
export const CULTURE_BOOK_PATH = "";
export const FAMILY_BOOK_PATH = "";
export const TEXT_BOOK_PATH = "";
export const SEARCH_PATH = "/search";

/*BREADCRUMB NAME MAP*/

export const BREADCRUMB_NAME_MAPPING = {
  [HOME_PATH]: "home",
  [PROFILE_PATH]: "profile",
  [BOOK_PATH]: "book",
  [CART_PATH]: "cart",
};

/*AVATAR SIZE*/

export const AVATAR_SIZE = {
  small: 40,
  large: 150,
};

/*CARD_DUMMY_DATA*/
export const SKILL_BOOKS = [
  {
    id: 695,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T20:20:37",
    name: "TIKTOK MARKETING",
    avatar: "https://cf.shopee.vn/file/a2ffec8b227096f35aeffc7199566550",
    price: 190000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 120,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 4,
  },
  {
    id: 595,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T20:20:57",
    name: "Kỹ năng đọc sách hiệu quả",
    avatar:
      "https://salt.tikicdn.com/ts/product/3d/2f/ae/53e3eba6cabdd47ed2920ffd2c474530.png",
    price: 200000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 400,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Tránh đọc nhảy trở lại quá nhiều. – Chuyển động mắt theo chiều thẳng đứng khi đọc. – Đọc với tốc độ biến đổi: Đoạn nào quan trọng thì đọc chậm, đọc kĩ; đoạn nào không quan trọng thì đọc nhanh, đọc lướt. – Cố gắng hiểu ý nghĩa của cả đoạn văn, đừng để ý đến từ, đến câu.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 2,
  },
  {
    id: 670,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Đọc vị khách hàng bằng tâm lý học hành vi",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/0c/6a/09/3840b9c7135f2050ab30bed7c7039717.jpg",
    price: 245000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Đọc Vị Khách Hàng Bằng Tâm Lý Học Hành Vi được viết dựa trên một quá trình nghiên cứu lâu dài được thực hiện bởi những nhà nghiên cứu về tâm lý học xã hội và các ngành khoa học khác, dựa trên thực nghiệm của hàng trăm người tài năng thuộc rất nhiều tổ chức khác nhau trên toàn thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 134,
    status: true,
    createdDate: "2021-03-27T15:47:09",
    updatedDate: "2022-11-16T18:35:09",
    name: "Trí tuệ cộng tác",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/19/1e/ed/a54f09671673fcdfe924e7bf854a680f.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Hãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?\r\n\r\nCUỐN SÁCH MANG LẠI CHO BẠN ĐIỀU GÌ\r\n\r\nMột phần tâm trí của chúng ta là sự giao thoa với những tâm trí khác. Khi mất đi sự hợp tác, con người mất đi sự gắn kết bề sâu của các mối quan hệ\r\n\r\nTâm trí của mỗi người đều có cách vận hành của riêng nó và chúng ta bất đồng quan điểm vì chúng ta không hiểu mình và không hiểu nhau, không biết cách suy nghĩ của mình và cách suy nghĩ của nhau\r\n\r\nTất cả những gì còn lại liên quan đến thế giới xung quanh chỉ là sự mù mờ, sự mơ hồ. Dù cánh cửa tư duy có đang đóng chặt, dù cánh cửa kết nối có đang khóa kín, chắc chắn sẽ có cách mở ra. Chẳng đâu xa, cuốn sách này chính là:\r\n\r\n•          Tấm bản đồ chi tiết về dạng thức tâm trí của bạn\r\n\r\n•          Chìa khóa giúp bạn đột phá ý tưởng nhờ định hướng mục tiêu\r\n\r\n•          Chỉ dẫn giúp bạn thay đổi và thiết lập trật tự cho cuộc sống\r\n\r\nTrí tuệ cộng tác sẽ đưa bạn từ quá khứ đến với tương lai, đó là một con đường dài, cần có người chung vai giúp sức. Việc chúng ta khác nhau không có nghĩa là phải có một người trong chúng ta là người sai. Điều đó đơn giản là không chỉ có một cách để đúng\r\n\r\nBởi vì câu hỏi thực sự cần đặt ra không phải là từng người có biểu hiện tốt đến đâu, mà là chúng ta có thể cùng nhau cộng tác làm việc hiệu quả tới mức nào\r\n\r\nThất bại và đổ vỡ đều bắt nguồn từ những lối mòn trong tư duy. Và đột phá bắt nguồn từ những suy nghĩ vượt ra khỏi các giới hạn của thói quen thông thường\r\n\r\nGiới hạn trong tư duy chắc chắn sẽ giới hạn con đường đi đến thành công của bạn. Cuốn sách này sẽ giúp bạn mở ra cánh cửa tâm trí đang bị đóng chặt, giúp bạn kết nối với thế giới xung quanh và HÒA NHỊP TƯ DUY, PHÁT HUY SỨC MẠNH ĐỘT PHÁ\r\n\r\nTHÔNG TIN TÁC GIẢ\r\n\r\nDAWNA MARKOVA, Ph.D\r\n\r\nCEO Danh dự của Tổ chức Professional Thinking PartnersTM .\r\n\r\nTiến sĩ Dawna Markova là một chuyên gia nổi tiếng quốc tế trong các lĩnh vực trị liệu tâm lí, nghiên cứu nhận thức và năng lực con người.\r\n\r\nTiến sĩ Markova là cựu thành viên cao cấp của Trung tâm Tổ chức Học tập (Organizational Learning Center) tại MIT và là thành viên tư vấn của Hiệp hội Tổ chức Học tập (Society for Organizational Learning). Bà đã thành lập các cộng đồng nghiên cứu trên khắp Hoa Kỳ, lãnh đạo các hội thảo về tối đa hóa tài năng cá nhân và đội nhóm, đóng vai trò là đối tác tư duy cho các CEO và giám đốc điều hành cấp cao trên toàn thế giới.\r\n\r\nTác phẩm:\r\n\r\nI Will Not Die an Unlived Life: Reclaiming Purpose and Passion (2000)\r\n\r\nRandom Acts of Kindness Series (2002)\r\n\r\nA Spot of Grace: Remarkable Stories Of How You DO Make a Difference (2008)\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting In a Disconnected World (2017) – đồng tác giả\r\n\r\nANGIE MCARTHUR​​​​​​​\r\n\r\nCEO của Tổ chức Professional Thinking PartnersTM (từ năm 1998 đến nay)\r\n\r\nCô là một chuyên gia nghiên cứu mô hình nhận thức nhận thức và phát triển các chiến lược truyền thông cho các nhà lãnh đạo và đội nhóm, từ các tổ chức từ phi lợi nhuận cho đến các công ty thuộc top 500 do tạp chí Fortune bình chọn.\r\n\r\nCô cũng là một trong những người tạo ra Mạng lưới Phụ nữ Toàn cầu (Worldwide Women’s Web) – thành lập năm 2001 nhằm kết nối các nữ lãnh đạo doanh nghiệp trên thế giới.\r\n\r\nTác phẩm:\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting in a Disconnected World (2017) – đồng tác giả.\r\n\r\nMã hàng\t9786045680513\r\nTên Nhà Cung Cấp\tBách Việt\r\nTác giả\tDawna Markova, PhD, Angie McArthur\r\nNgười Dịch\tNguyễn Nguyên Khôi\r\nNXB\tNXB Phụ Nữ Việt Nam\r\nNăm XB\t2020\r\nTrọng lượng (gr)\t530\r\nKích Thước Bao Bì\t20 x 13.5 cm\r\nSố trang\t528\r\nHình thức\tBìa Mềm\r\nSản phẩm hiển thị trong\t\r\nBách Việt\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Tâm lý bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nTRÍ TUỆ CỘNG TÁC - Collabrotive Intelligence\r\n\r\nHãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?",
    slug: "tri-tue-cong-tac-1619853982481",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 62,
  },
  {
    id: 495,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:27:01",
    name: "Trí tuệ cộng tác",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/19/1e/ed/a54f09671673fcdfe924e7bf854a680f.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Hãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?\r\n\r\nCUỐN SÁCH MANG LẠI CHO BẠN ĐIỀU GÌ\r\n\r\nMột phần tâm trí của chúng ta là sự giao thoa với những tâm trí khác. Khi mất đi sự hợp tác, con người mất đi sự gắn kết bề sâu của các mối quan hệ\r\n\r\nTâm trí của mỗi người đều có cách vận hành của riêng nó và chúng ta bất đồng quan điểm vì chúng ta không hiểu mình và không hiểu nhau, không biết cách suy nghĩ của mình và cách suy nghĩ của nhau\r\n\r\nTất cả những gì còn lại liên quan đến thế giới xung quanh chỉ là sự mù mờ, sự mơ hồ. Dù cánh cửa tư duy có đang đóng chặt, dù cánh cửa kết nối có đang khóa kín, chắc chắn sẽ có cách mở ra. Chẳng đâu xa, cuốn sách này chính là:\r\n\r\n•          Tấm bản đồ chi tiết về dạng thức tâm trí của bạn\r\n\r\n•          Chìa khóa giúp bạn đột phá ý tưởng nhờ định hướng mục tiêu\r\n\r\n•          Chỉ dẫn giúp bạn thay đổi và thiết lập trật tự cho cuộc sống\r\n\r\nTrí tuệ cộng tác sẽ đưa bạn từ quá khứ đến với tương lai, đó là một con đường dài, cần có người chung vai giúp sức. Việc chúng ta khác nhau không có nghĩa là phải có một người trong chúng ta là người sai. Điều đó đơn giản là không chỉ có một cách để đúng\r\n\r\nBởi vì câu hỏi thực sự cần đặt ra không phải là từng người có biểu hiện tốt đến đâu, mà là chúng ta có thể cùng nhau cộng tác làm việc hiệu quả tới mức nào\r\n\r\nThất bại và đổ vỡ đều bắt nguồn từ những lối mòn trong tư duy. Và đột phá bắt nguồn từ những suy nghĩ vượt ra khỏi các giới hạn của thói quen thông thường\r\n\r\nGiới hạn trong tư duy chắc chắn sẽ giới hạn con đường đi đến thành công của bạn. Cuốn sách này sẽ giúp bạn mở ra cánh cửa tâm trí đang bị đóng chặt, giúp bạn kết nối với thế giới xung quanh và HÒA NHỊP TƯ DUY, PHÁT HUY SỨC MẠNH ĐỘT PHÁ\r\n\r\nTHÔNG TIN TÁC GIẢ\r\n\r\nDAWNA MARKOVA, Ph.D\r\n\r\nCEO Danh dự của Tổ chức Professional Thinking PartnersTM .\r\n\r\nTiến sĩ Dawna Markova là một chuyên gia nổi tiếng quốc tế trong các lĩnh vực trị liệu tâm lí, nghiên cứu nhận thức và năng lực con người.\r\n\r\nTiến sĩ Markova là cựu thành viên cao cấp của Trung tâm Tổ chức Học tập (Organizational Learning Center) tại MIT và là thành viên tư vấn của Hiệp hội Tổ chức Học tập (Society for Organizational Learning). Bà đã thành lập các cộng đồng nghiên cứu trên khắp Hoa Kỳ, lãnh đạo các hội thảo về tối đa hóa tài năng cá nhân và đội nhóm, đóng vai trò là đối tác tư duy cho các CEO và giám đốc điều hành cấp cao trên toàn thế giới.\r\n\r\nTác phẩm:\r\n\r\nI Will Not Die an Unlived Life: Reclaiming Purpose and Passion (2000)\r\n\r\nRandom Acts of Kindness Series (2002)\r\n\r\nA Spot of Grace: Remarkable Stories Of How You DO Make a Difference (2008)\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting In a Disconnected World (2017) – đồng tác giả\r\n\r\nANGIE MCARTHUR​​​​​​​\r\n\r\nCEO của Tổ chức Professional Thinking PartnersTM (từ năm 1998 đến nay)\r\n\r\nCô là một chuyên gia nghiên cứu mô hình nhận thức nhận thức và phát triển các chiến lược truyền thông cho các nhà lãnh đạo và đội nhóm, từ các tổ chức từ phi lợi nhuận cho đến các công ty thuộc top 500 do tạp chí Fortune bình chọn.\r\n\r\nCô cũng là một trong những người tạo ra Mạng lưới Phụ nữ Toàn cầu (Worldwide Women’s Web) – thành lập năm 2001 nhằm kết nối các nữ lãnh đạo doanh nghiệp trên thế giới.\r\n\r\nTác phẩm:\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting in a Disconnected World (2017) – đồng tác giả.\r\n\r\nMã hàng\t9786045680513\r\nTên Nhà Cung Cấp\tBách Việt\r\nTác giả\tDawna Markova, PhD, Angie McArthur\r\nNgười Dịch\tNguyễn Nguyên Khôi\r\nNXB\tNXB Phụ Nữ Việt Nam\r\nNăm XB\t2020\r\nTrọng lượng (gr)\t530\r\nKích Thước Bao Bì\t20 x 13.5 cm\r\nSố trang\t528\r\nHình thức\tBìa Mềm\r\nSản phẩm hiển thị trong\t\r\nBách Việt\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Tâm lý bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nTRÍ TUỆ CỘNG TÁC - Collabrotive Intelligence\r\n\r\nHãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 645,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Rèn luyện tư duy tích cực",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/bc/a2/be/3c8423bd287895f5c47257b51cd15349.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Đọc Vị Khách Hàng Bằng Tâm Lý Học Hành Vi được viết dựa trên một quá trình nghiên cứu lâu dài được thực hiện bởi những nhà nghiên cứu về tâm lý học xã hội và các ngành khoa học khác, dựa trên thực nghiệm của hàng trăm người tài năng thuộc rất nhiều tổ chức khác nhau trên toàn thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 745,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Đừng bán hàng bán sự khác biệt",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/7d/3a/5b/10bbb6a464b1fd7a80af41c737d10288.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 199,
    language: "Tiếng Ahh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Khác biệt trong bán hàng không phải là làm thế nào để trở nên độc nhất mà là phải trở nên khác biệt.\r\n\r\nTrong thế giới kinh doanh khốc liệt với hàng tá đối thủ cạnh tranh, làm thế nào để nhân viên bán hàng và công ty của bạn có thể trở nên khác biệt và nắm chắc phần thắng trong tay. \r\n\r\nBạn sẽ phải hạ giá sản phẩm hay dịch vụ của mình ư? \r\n\r\nBạn sẽ phải chiều theo ý muốn của khách hàng và không thể làm chủ được cuộc giao dịch này?\r\n\r\n Hay ngược lại bạn có thể định hình tiêu chí quyết định của người mua, trở nên khác biệt chứ không phải độc nhất? \r\n\r\nĐiểm khác biệt đầy sức hấp dẫn chính là BẠN…\r\n\r\nHãy biến điều đó trở nên vô giá.\r\n\r\nVà “Đừng bán hàng – Bán sự khác biệt” sẽ cho bạn thấy 19 tuyệt chiêu chốt sale khiến khách hàng không thể chối từ.\r\n\r\nGiá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 819,
    status: false,
    createdDate: "2022-11-16T17:27:03",
    updatedDate: "2022-11-16T17:27:03",
    name: "Phong cách quản lý và giữ chân nhân tài của người Nhật",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/6b/25/41/7c13046564f7f0ace99c6589605bfd01.jpg",
    price: 250000.0,
    dimension: "25 x 30 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Ngoại Ngữ ",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Phong Cách Quản Lý Và Giữ Chân Nhân Tài Của Người Nhật \r\n\r\n“Phong cách quản lý và giữ chân nhân tài của người Nhật” là một cuốn sách hướng đến đối tượng độc giả là những người đang đảm nhiệm vị trí lãnh đạo, quản lý cũng như những người sắp trở thành nhà lãnh đạo.\r\n\r\nCuốn sách bao gồm 60 nội dung thảo luận chuyên đạo cần chú tâm tìm hiểu sâu, tổng kết tất cả những chủ đề chính mà một nhà lãnh đạo trong hành trình dẫn dắt nhân sự cũng như điều hành doanh nghiệp. Không chỉ cung cấp thông tin hữu ích để người đọc trở thành một nhà lãnh đạo sáng suốt, giúp độc giả xây dựng được những tư tưởng mang tính cá nhân, mà tác giả Sugiura còn truyền động lực để thúc giục người đọc thật sự hành động thông qua những lời khuyên và các bước áp dụng cụ thể.\r\n\r\nKhông giống như nhiều cuốn sách khác có cùng chủ đề, nhưng chỉ dừng lại ở lý thuyết khái quát, “Phong cách quản lý và giữ chân nhân tài của người Nhật” có ba đặc điểm chính khác biệt sau:\r\n\r\nCác chủ đề được bàn luận đều tập trung vào hành động, để nhấn mạnh tầm quan trọng của thực tiễn, hay khả năng áp dụng các phương pháp giải quyết vấn đề vào tình huống thực tế.\r\n\r\nCuốn sách cung cấp nhiều biểu đồ minh họa để trực quan hóa lý thuyết, giúp độc giả nhanh chóng nắm bắt được các điểm then chốt",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 135,
    status: true,
    createdDate: "2021-03-27T15:48:34",
    updatedDate: null,
    name: "Work-life balance: Khi người trẻ cần cảm hứng và kế hoạch để theo đuổi sự nghiệp",
    avatar:
      "https://lzd-img-global.slatic.net/g/p/575c9f97b4ca53b7846b761ea6b74417.png_1200x1200q80.jpg_.webp",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 8,
    hot: false,
    act: true,
    buyCount: 1,
    desc: "Work-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.\r\n\r\nKhông chỉ phù hợp với những doanh nhân và lãnh đạo cấp cao, bộ công cụ có trong tác phẩm “Work-Life Balance” khả dụng với tất cả mọi người, đặc biệt là với những bạn trẻ - những người luôn cần cảm hứng và một kế hoạch sáng suốt để theo đuổi sự nghiệp.\r\n\r\nVề tác giả: Randi Zuckerberg là doanh nhân, nhà văn, người có tiếng nói trong giới công nghệ. Cô là cựu giám đốc phát triển thị trường và phát ngôn viên của Facebook, chị gái của CEO Facebook Mark Zuckerberg. Randi thường xuyên được mời diễn thuyết về công nghệ, kinh doanh và nữ quyền trong kinh doanh trên khắp thế giới.\r\n\r\nMã hàng\t8936066686082\r\nTên Nhà Cung Cấp\t1980 Books\r\nTác giả\tRandi Zuckerberg\r\nNgười Dịch\tMinh Nga Feehily\r\nNXB\tNXB Lao Động\r\nNăm XB\t2018\r\nTrọng lượng (gr)\t380\r\nKích Thước Bao Bì\t13 x 20\r\nSố trang\t360\r\nHình thức\tBìa Mềm\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Kỹ năng sống bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nWork-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.",
    slug: "work-life-balance-khi-nguoi-tre-can-cam-hung-va-ke-hoach-de-theo-duoi-su-nghiep-1619853989257",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 61,
  },
  {
    id: 520,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:46:44",
    name: "Work-life balance: Khi người trẻ cần cảm hứng và kế hoạch để theo đuổi sự nghiệp",
    avatar:
      "https://lzd-img-global.slatic.net/g/p/575c9f97b4ca53b7846b761ea6b74417.png_1200x1200q80.jpg_.webp",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Work-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.\r\n\r\nKhông chỉ phù hợp với những doanh nhân và lãnh đạo cấp cao, bộ công cụ có trong tác phẩm “Work-Life Balance” khả dụng với tất cả mọi người, đặc biệt là với những bạn trẻ - những người luôn cần cảm hứng và một kế hoạch sáng suốt để theo đuổi sự nghiệp.\r\n\r\nVề tác giả: Randi Zuckerberg là doanh nhân, nhà văn, người có tiếng nói trong giới công nghệ. Cô là cựu giám đốc phát triển thị trường và phát ngôn viên của Facebook, chị gái của CEO Facebook Mark Zuckerberg. Randi thường xuyên được mời diễn thuyết về công nghệ, kinh doanh và nữ quyền trong kinh doanh trên khắp thế giới.\r\n\r\nMã hàng\t8936066686082\r\nTên Nhà Cung Cấp\t1980 Books\r\nTác giả\tRandi Zuckerberg\r\nNgười Dịch\tMinh Nga Feehily\r\nNXB\tNXB Lao Động\r\nNăm XB\t2018\r\nTrọng lượng (gr)\t380\r\nKích Thước Bao Bì\t13 x 20\r\nSố trang\t360\r\nHình thức\tBìa Mềm\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Kỹ năng sống bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nWork-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 1,
  },
];

export const DETECTIVE_BOOKS = [
  {
    id: 703,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "TIKTOK MARKETING",
    avatar: "https://cf.shopee.vn/file/a2ffec8b227096f35aeffc7199566550",
    price: 190000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 120,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 603,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:27:01",
    name: "Kỹ năng đọc sách hiệu quả",
    avatar:
      "https://salt.tikicdn.com/ts/product/3d/2f/ae/53e3eba6cabdd47ed2920ffd2c474530.png",
    price: 200000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 400,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Tránh đọc nhảy trở lại quá nhiều. – Chuyển động mắt theo chiều thẳng đứng khi đọc. – Đọc với tốc độ biến đổi: Đoạn nào quan trọng thì đọc chậm, đọc kĩ; đoạn nào không quan trọng thì đọc nhanh, đọc lướt. – Cố gắng hiểu ý nghĩa của cả đoạn văn, đừng để ý đến từ, đến câu.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 678,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Đọc vị khách hàng bằng tâm lý học hành vi",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/0c/6a/09/3840b9c7135f2050ab30bed7c7039717.jpg",
    price: 245000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Đọc Vị Khách Hàng Bằng Tâm Lý Học Hành Vi được viết dựa trên một quá trình nghiên cứu lâu dài được thực hiện bởi những nhà nghiên cứu về tâm lý học xã hội và các ngành khoa học khác, dựa trên thực nghiệm của hàng trăm người tài năng thuộc rất nhiều tổ chức khác nhau trên toàn thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 503,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:27:01",
    name: "Trí tuệ cộng tác",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/19/1e/ed/a54f09671673fcdfe924e7bf854a680f.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Hãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?\r\n\r\nCUỐN SÁCH MANG LẠI CHO BẠN ĐIỀU GÌ\r\n\r\nMột phần tâm trí của chúng ta là sự giao thoa với những tâm trí khác. Khi mất đi sự hợp tác, con người mất đi sự gắn kết bề sâu của các mối quan hệ\r\n\r\nTâm trí của mỗi người đều có cách vận hành của riêng nó và chúng ta bất đồng quan điểm vì chúng ta không hiểu mình và không hiểu nhau, không biết cách suy nghĩ của mình và cách suy nghĩ của nhau\r\n\r\nTất cả những gì còn lại liên quan đến thế giới xung quanh chỉ là sự mù mờ, sự mơ hồ. Dù cánh cửa tư duy có đang đóng chặt, dù cánh cửa kết nối có đang khóa kín, chắc chắn sẽ có cách mở ra. Chẳng đâu xa, cuốn sách này chính là:\r\n\r\n•          Tấm bản đồ chi tiết về dạng thức tâm trí của bạn\r\n\r\n•          Chìa khóa giúp bạn đột phá ý tưởng nhờ định hướng mục tiêu\r\n\r\n•          Chỉ dẫn giúp bạn thay đổi và thiết lập trật tự cho cuộc sống\r\n\r\nTrí tuệ cộng tác sẽ đưa bạn từ quá khứ đến với tương lai, đó là một con đường dài, cần có người chung vai giúp sức. Việc chúng ta khác nhau không có nghĩa là phải có một người trong chúng ta là người sai. Điều đó đơn giản là không chỉ có một cách để đúng\r\n\r\nBởi vì câu hỏi thực sự cần đặt ra không phải là từng người có biểu hiện tốt đến đâu, mà là chúng ta có thể cùng nhau cộng tác làm việc hiệu quả tới mức nào\r\n\r\nThất bại và đổ vỡ đều bắt nguồn từ những lối mòn trong tư duy. Và đột phá bắt nguồn từ những suy nghĩ vượt ra khỏi các giới hạn của thói quen thông thường\r\n\r\nGiới hạn trong tư duy chắc chắn sẽ giới hạn con đường đi đến thành công của bạn. Cuốn sách này sẽ giúp bạn mở ra cánh cửa tâm trí đang bị đóng chặt, giúp bạn kết nối với thế giới xung quanh và HÒA NHỊP TƯ DUY, PHÁT HUY SỨC MẠNH ĐỘT PHÁ\r\n\r\nTHÔNG TIN TÁC GIẢ\r\n\r\nDAWNA MARKOVA, Ph.D\r\n\r\nCEO Danh dự của Tổ chức Professional Thinking PartnersTM .\r\n\r\nTiến sĩ Dawna Markova là một chuyên gia nổi tiếng quốc tế trong các lĩnh vực trị liệu tâm lí, nghiên cứu nhận thức và năng lực con người.\r\n\r\nTiến sĩ Markova là cựu thành viên cao cấp của Trung tâm Tổ chức Học tập (Organizational Learning Center) tại MIT và là thành viên tư vấn của Hiệp hội Tổ chức Học tập (Society for Organizational Learning). Bà đã thành lập các cộng đồng nghiên cứu trên khắp Hoa Kỳ, lãnh đạo các hội thảo về tối đa hóa tài năng cá nhân và đội nhóm, đóng vai trò là đối tác tư duy cho các CEO và giám đốc điều hành cấp cao trên toàn thế giới.\r\n\r\nTác phẩm:\r\n\r\nI Will Not Die an Unlived Life: Reclaiming Purpose and Passion (2000)\r\n\r\nRandom Acts of Kindness Series (2002)\r\n\r\nA Spot of Grace: Remarkable Stories Of How You DO Make a Difference (2008)\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting In a Disconnected World (2017) – đồng tác giả\r\n\r\nANGIE MCARTHUR​​​​​​​\r\n\r\nCEO của Tổ chức Professional Thinking PartnersTM (từ năm 1998 đến nay)\r\n\r\nCô là một chuyên gia nghiên cứu mô hình nhận thức nhận thức và phát triển các chiến lược truyền thông cho các nhà lãnh đạo và đội nhóm, từ các tổ chức từ phi lợi nhuận cho đến các công ty thuộc top 500 do tạp chí Fortune bình chọn.\r\n\r\nCô cũng là một trong những người tạo ra Mạng lưới Phụ nữ Toàn cầu (Worldwide Women’s Web) – thành lập năm 2001 nhằm kết nối các nữ lãnh đạo doanh nghiệp trên thế giới.\r\n\r\nTác phẩm:\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting in a Disconnected World (2017) – đồng tác giả.\r\n\r\nMã hàng\t9786045680513\r\nTên Nhà Cung Cấp\tBách Việt\r\nTác giả\tDawna Markova, PhD, Angie McArthur\r\nNgười Dịch\tNguyễn Nguyên Khôi\r\nNXB\tNXB Phụ Nữ Việt Nam\r\nNăm XB\t2020\r\nTrọng lượng (gr)\t530\r\nKích Thước Bao Bì\t20 x 13.5 cm\r\nSố trang\t528\r\nHình thức\tBìa Mềm\r\nSản phẩm hiển thị trong\t\r\nBách Việt\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Tâm lý bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nTRÍ TUỆ CỘNG TÁC - Collabrotive Intelligence\r\n\r\nHãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 653,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Rèn luyện tư duy tích cực",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/bc/a2/be/3c8423bd287895f5c47257b51cd15349.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Đọc Vị Khách Hàng Bằng Tâm Lý Học Hành Vi được viết dựa trên một quá trình nghiên cứu lâu dài được thực hiện bởi những nhà nghiên cứu về tâm lý học xã hội và các ngành khoa học khác, dựa trên thực nghiệm của hàng trăm người tài năng thuộc rất nhiều tổ chức khác nhau trên toàn thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 753,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Đừng bán hàng bán sự khác biệt",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/7d/3a/5b/10bbb6a464b1fd7a80af41c737d10288.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 199,
    language: "Tiếng Ahh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Khác biệt trong bán hàng không phải là làm thế nào để trở nên độc nhất mà là phải trở nên khác biệt.\r\n\r\nTrong thế giới kinh doanh khốc liệt với hàng tá đối thủ cạnh tranh, làm thế nào để nhân viên bán hàng và công ty của bạn có thể trở nên khác biệt và nắm chắc phần thắng trong tay. \r\n\r\nBạn sẽ phải hạ giá sản phẩm hay dịch vụ của mình ư? \r\n\r\nBạn sẽ phải chiều theo ý muốn của khách hàng và không thể làm chủ được cuộc giao dịch này?\r\n\r\n Hay ngược lại bạn có thể định hình tiêu chí quyết định của người mua, trở nên khác biệt chứ không phải độc nhất? \r\n\r\nĐiểm khác biệt đầy sức hấp dẫn chính là BẠN…\r\n\r\nHãy biến điều đó trở nên vô giá.\r\n\r\nVà “Đừng bán hàng – Bán sự khác biệt” sẽ cho bạn thấy 19 tuyệt chiêu chốt sale khiến khách hàng không thể chối từ.\r\n\r\nGiá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 825,
    status: false,
    createdDate: "2022-11-16T17:27:03",
    updatedDate: "2022-11-16T17:27:03",
    name: "Phong cách quản lý và giữ chân nhân tài của người Nhật",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/6b/25/41/7c13046564f7f0ace99c6589605bfd01.jpg",
    price: 250000.0,
    dimension: "25 x 30 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Ngoại Ngữ ",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Phong Cách Quản Lý Và Giữ Chân Nhân Tài Của Người Nhật \r\n\r\n“Phong cách quản lý và giữ chân nhân tài của người Nhật” là một cuốn sách hướng đến đối tượng độc giả là những người đang đảm nhiệm vị trí lãnh đạo, quản lý cũng như những người sắp trở thành nhà lãnh đạo.\r\n\r\nCuốn sách bao gồm 60 nội dung thảo luận chuyên đạo cần chú tâm tìm hiểu sâu, tổng kết tất cả những chủ đề chính mà một nhà lãnh đạo trong hành trình dẫn dắt nhân sự cũng như điều hành doanh nghiệp. Không chỉ cung cấp thông tin hữu ích để người đọc trở thành một nhà lãnh đạo sáng suốt, giúp độc giả xây dựng được những tư tưởng mang tính cá nhân, mà tác giả Sugiura còn truyền động lực để thúc giục người đọc thật sự hành động thông qua những lời khuyên và các bước áp dụng cụ thể.\r\n\r\nKhông giống như nhiều cuốn sách khác có cùng chủ đề, nhưng chỉ dừng lại ở lý thuyết khái quát, “Phong cách quản lý và giữ chân nhân tài của người Nhật” có ba đặc điểm chính khác biệt sau:\r\n\r\nCác chủ đề được bàn luận đều tập trung vào hành động, để nhấn mạnh tầm quan trọng của thực tiễn, hay khả năng áp dụng các phương pháp giải quyết vấn đề vào tình huống thực tế.\r\n\r\nCuốn sách cung cấp nhiều biểu đồ minh họa để trực quan hóa lý thuyết, giúp độc giả nhanh chóng nắm bắt được các điểm then chốt",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 152,
    status: true,
    createdDate: "2021-04-17T16:33:10",
    updatedDate: "2022-11-16T17:14:26",
    name: "Tiểu Thuyết Trinh Thám 1/14 ",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/8b/95/af/f405d953b508fe89c314f9fdd99911bd.jpg",
    price: 280000.0,
    dimension: "25 x 30 cm",
    format: "Bìa cứng",
    totalPage: 290,
    language: "Tiếng Việt",
    publicationDate: "2021-04-17T00:00:00",
    discount: 8,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "1/14 là một trò chơi kì lạ. Đây là một trò chơi thử thách trí tuệ và lòng dũng cảm, người thắng cuộc sẽ giành được phần thưởng vô cùng lớn và quyền được sinh tồn, còn những kẻ vi phạm nguyên tắc trò chơi sẽ phải nhận sự trừng phạt chính là cái chết.\r\n\r\nMười bốn tác giả chuyên viết tiểu thuyết trinh thám bị “mời” đến một nơi bí mật, những tình huống kì lạ xảy ra, những sự kiện đáng sợ và bất ngờ liên tục xuất hiện, khiến họ không tài nào lí giải nổi. Cái chết luôn rình rập mọi lúc, mọi nơi, không khí căng thẳng bao trùm. Khi số người sống sót càng ngày càng ít, họ dần nhận ra một “quy luật” và bí mật kinh người…\r\n\r\n“Trò chơi tử thần” đã bắt đầu, kẻ chủ mưu vẫn lẩn khuất xung quanh họ là ai? Hắn ta? Cô ta? Rốt cục có mục đích gì? Sau mười bốn ngày, có ai còn sống sót và thoát khỏi nơi quỉ quái đó hay không? Liệu sau đó còn có điều gì đáng sợ hơn chăng? Đó lẽ nào là một trò chơi không bao giờ kết thúc?\r\n\r\nHãy nhớ rằng, kể từ khi mở trang đầu tiên, bạn đã trở thành một nhân vật trong trò chơi đó!\r\n\r\nGiá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: "tieu-thuyet-trinh-tham-1-14-1619854149520",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 63,
  },
  {
    id: 528,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:27:01",
    name: "Work-life balance: Khi người trẻ cần cảm hứng và kế hoạch để theo đuổi sự nghiệp",
    avatar:
      "https://lzd-img-global.slatic.net/g/p/575c9f97b4ca53b7846b761ea6b74417.png_1200x1200q80.jpg_.webp",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Work-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.\r\n\r\nKhông chỉ phù hợp với những doanh nhân và lãnh đạo cấp cao, bộ công cụ có trong tác phẩm “Work-Life Balance” khả dụng với tất cả mọi người, đặc biệt là với những bạn trẻ - những người luôn cần cảm hứng và một kế hoạch sáng suốt để theo đuổi sự nghiệp.\r\n\r\nVề tác giả: Randi Zuckerberg là doanh nhân, nhà văn, người có tiếng nói trong giới công nghệ. Cô là cựu giám đốc phát triển thị trường và phát ngôn viên của Facebook, chị gái của CEO Facebook Mark Zuckerberg. Randi thường xuyên được mời diễn thuyết về công nghệ, kinh doanh và nữ quyền trong kinh doanh trên khắp thế giới.\r\n\r\nMã hàng\t8936066686082\r\nTên Nhà Cung Cấp\t1980 Books\r\nTác giả\tRandi Zuckerberg\r\nNgười Dịch\tMinh Nga Feehily\r\nNXB\tNXB Lao Động\r\nNăm XB\t2018\r\nTrọng lượng (gr)\t380\r\nKích Thước Bao Bì\t13 x 20\r\nSố trang\t360\r\nHình thức\tBìa Mềm\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Kỹ năng sống bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nWork-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 728,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Content marketing trong kỉ nguyên trải nghiệm khách hàng",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/13/32/f2/e4079c2ab39e9a4c42eeefed2bd4ab1c.jpg",
    price: 290000.0,
    dimension: "25 x 30 cm",
    format: "Bìa cứng",
    totalPage: 202,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
];

export const SCIENCE_BOOKS = [
  {
    id: 707,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "TIKTOK MARKETING",
    avatar: "https://cf.shopee.vn/file/a2ffec8b227096f35aeffc7199566550",
    price: 190000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 120,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 607,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:27:01",
    name: "Kỹ năng đọc sách hiệu quả",
    avatar:
      "https://salt.tikicdn.com/ts/product/3d/2f/ae/53e3eba6cabdd47ed2920ffd2c474530.png",
    price: 200000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 400,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Tránh đọc nhảy trở lại quá nhiều. – Chuyển động mắt theo chiều thẳng đứng khi đọc. – Đọc với tốc độ biến đổi: Đoạn nào quan trọng thì đọc chậm, đọc kĩ; đoạn nào không quan trọng thì đọc nhanh, đọc lướt. – Cố gắng hiểu ý nghĩa của cả đoạn văn, đừng để ý đến từ, đến câu.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 166,
    status: true,
    createdDate: "2021-05-12T11:44:30",
    updatedDate: "2022-11-16T16:54:21",
    name: "Neymar - Thiên tài tranh cãi",
    avatar: "https://thbooks.vn/hm_content/uploads/Neymar_2D.jpg",
    price: 230000.0,
    dimension: "25 x 30 cm",
    format: "Bìa cứng",
    totalPage: 120,
    language: "Tiếng Anh",
    publicationDate: "2021-05-12T00:00:00",
    discount: 8,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Cậu ấy có tất cả những phẩm chất của một cầu thủ vĩ đại: cậu ấy rê bóng rất giỏi, ở tốc độ cao; cậu ấy chuyển hướng một cách thanh thoát; cậu ấy có thể dẫn bóng bằng chân trái hay chân phải; cậu ấy có một lực sút tốt; cậu ấy rất nhanh, sáng tạo, thông minh và có sự chính xác ổn định trong những pha dứt điểm cả trong lẫn ngoài vòng cấm; cậu ấy là một goleador (tay săn bàn hàng đầu); cậu ấy có thể ghi bàn bằng chân trái hay chân phải, bằng đầu, hay từ một quả đá phạt; cậu ấy đá phạt góc rất hay, có thể đưa bóng cuộn vào vòng cấm. Có lẽ phẩm chất tuyệt vời nhất, điều làm nên sự khác biệt so với các ngôi sao khác, là khả năng rê bóng và ghi bàn bằng cả hai chân - điều mà tôi chỉ mới thấy có Pelé làm được.",
    slug: "neymar-thien-tai-tranh-cai-1620794670120",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 92,
  },
  {
    id: 682,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Đọc vị khách hàng bằng tâm lý học hành vi",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/0c/6a/09/3840b9c7135f2050ab30bed7c7039717.jpg",
    price: 245000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Đọc Vị Khách Hàng Bằng Tâm Lý Học Hành Vi được viết dựa trên một quá trình nghiên cứu lâu dài được thực hiện bởi những nhà nghiên cứu về tâm lý học xã hội và các ngành khoa học khác, dựa trên thực nghiệm của hàng trăm người tài năng thuộc rất nhiều tổ chức khác nhau trên toàn thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 165,
    status: true,
    createdDate: "2021-05-12T11:41:47",
    updatedDate: "2021-05-12T11:42:18",
    name: "Mbappe - Cậu bé vàng",
    avatar: "https://cf.shopee.vn/file/f13213596aaaadc46f488e09a2f67a81",
    price: 250000.0,
    dimension: "22 x 35 cm",
    format: "Bìa mềm",
    totalPage: 290,
    language: "Tiếng Việt",
    publicationDate: "2021-05-12T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Những điều diệu kỳ từ tư tưởng và triết lý sống Khổng Tử Tác giả Yu Dan là người Bắc Kinh, thạc sĩ văn học cổ điển Trung Quốc, tiến sĩ ngành điện ảnh-truyền hình.\r\n",
    slug: "mbappe-cau-be-vang-1620794537850",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 62,
  },
  {
    id: 507,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:27:01",
    name: "Trí tuệ cộng tác",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/19/1e/ed/a54f09671673fcdfe924e7bf854a680f.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Hãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?\r\n\r\nCUỐN SÁCH MANG LẠI CHO BẠN ĐIỀU GÌ\r\n\r\nMột phần tâm trí của chúng ta là sự giao thoa với những tâm trí khác. Khi mất đi sự hợp tác, con người mất đi sự gắn kết bề sâu của các mối quan hệ\r\n\r\nTâm trí của mỗi người đều có cách vận hành của riêng nó và chúng ta bất đồng quan điểm vì chúng ta không hiểu mình và không hiểu nhau, không biết cách suy nghĩ của mình và cách suy nghĩ của nhau\r\n\r\nTất cả những gì còn lại liên quan đến thế giới xung quanh chỉ là sự mù mờ, sự mơ hồ. Dù cánh cửa tư duy có đang đóng chặt, dù cánh cửa kết nối có đang khóa kín, chắc chắn sẽ có cách mở ra. Chẳng đâu xa, cuốn sách này chính là:\r\n\r\n•          Tấm bản đồ chi tiết về dạng thức tâm trí của bạn\r\n\r\n•          Chìa khóa giúp bạn đột phá ý tưởng nhờ định hướng mục tiêu\r\n\r\n•          Chỉ dẫn giúp bạn thay đổi và thiết lập trật tự cho cuộc sống\r\n\r\nTrí tuệ cộng tác sẽ đưa bạn từ quá khứ đến với tương lai, đó là một con đường dài, cần có người chung vai giúp sức. Việc chúng ta khác nhau không có nghĩa là phải có một người trong chúng ta là người sai. Điều đó đơn giản là không chỉ có một cách để đúng\r\n\r\nBởi vì câu hỏi thực sự cần đặt ra không phải là từng người có biểu hiện tốt đến đâu, mà là chúng ta có thể cùng nhau cộng tác làm việc hiệu quả tới mức nào\r\n\r\nThất bại và đổ vỡ đều bắt nguồn từ những lối mòn trong tư duy. Và đột phá bắt nguồn từ những suy nghĩ vượt ra khỏi các giới hạn của thói quen thông thường\r\n\r\nGiới hạn trong tư duy chắc chắn sẽ giới hạn con đường đi đến thành công của bạn. Cuốn sách này sẽ giúp bạn mở ra cánh cửa tâm trí đang bị đóng chặt, giúp bạn kết nối với thế giới xung quanh và HÒA NHỊP TƯ DUY, PHÁT HUY SỨC MẠNH ĐỘT PHÁ\r\n\r\nTHÔNG TIN TÁC GIẢ\r\n\r\nDAWNA MARKOVA, Ph.D\r\n\r\nCEO Danh dự của Tổ chức Professional Thinking PartnersTM .\r\n\r\nTiến sĩ Dawna Markova là một chuyên gia nổi tiếng quốc tế trong các lĩnh vực trị liệu tâm lí, nghiên cứu nhận thức và năng lực con người.\r\n\r\nTiến sĩ Markova là cựu thành viên cao cấp của Trung tâm Tổ chức Học tập (Organizational Learning Center) tại MIT và là thành viên tư vấn của Hiệp hội Tổ chức Học tập (Society for Organizational Learning). Bà đã thành lập các cộng đồng nghiên cứu trên khắp Hoa Kỳ, lãnh đạo các hội thảo về tối đa hóa tài năng cá nhân và đội nhóm, đóng vai trò là đối tác tư duy cho các CEO và giám đốc điều hành cấp cao trên toàn thế giới.\r\n\r\nTác phẩm:\r\n\r\nI Will Not Die an Unlived Life: Reclaiming Purpose and Passion (2000)\r\n\r\nRandom Acts of Kindness Series (2002)\r\n\r\nA Spot of Grace: Remarkable Stories Of How You DO Make a Difference (2008)\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting In a Disconnected World (2017) – đồng tác giả\r\n\r\nANGIE MCARTHUR​​​​​​​\r\n\r\nCEO của Tổ chức Professional Thinking PartnersTM (từ năm 1998 đến nay)\r\n\r\nCô là một chuyên gia nghiên cứu mô hình nhận thức nhận thức và phát triển các chiến lược truyền thông cho các nhà lãnh đạo và đội nhóm, từ các tổ chức từ phi lợi nhuận cho đến các công ty thuộc top 500 do tạp chí Fortune bình chọn.\r\n\r\nCô cũng là một trong những người tạo ra Mạng lưới Phụ nữ Toàn cầu (Worldwide Women’s Web) – thành lập năm 2001 nhằm kết nối các nữ lãnh đạo doanh nghiệp trên thế giới.\r\n\r\nTác phẩm:\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting in a Disconnected World (2017) – đồng tác giả.\r\n\r\nMã hàng\t9786045680513\r\nTên Nhà Cung Cấp\tBách Việt\r\nTác giả\tDawna Markova, PhD, Angie McArthur\r\nNgười Dịch\tNguyễn Nguyên Khôi\r\nNXB\tNXB Phụ Nữ Việt Nam\r\nNăm XB\t2020\r\nTrọng lượng (gr)\t530\r\nKích Thước Bao Bì\t20 x 13.5 cm\r\nSố trang\t528\r\nHình thức\tBìa Mềm\r\nSản phẩm hiển thị trong\t\r\nBách Việt\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Tâm lý bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nTRÍ TUỆ CỘNG TÁC - Collabrotive Intelligence\r\n\r\nHãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 657,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Rèn luyện tư duy tích cực",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/bc/a2/be/3c8423bd287895f5c47257b51cd15349.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Đọc Vị Khách Hàng Bằng Tâm Lý Học Hành Vi được viết dựa trên một quá trình nghiên cứu lâu dài được thực hiện bởi những nhà nghiên cứu về tâm lý học xã hội và các ngành khoa học khác, dựa trên thực nghiệm của hàng trăm người tài năng thuộc rất nhiều tổ chức khác nhau trên toàn thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 757,
    status: false,
    createdDate: "2022-11-16T17:27:02",
    updatedDate: "2022-11-16T17:27:02",
    name: "Đừng bán hàng bán sự khác biệt",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/7d/3a/5b/10bbb6a464b1fd7a80af41c737d10288.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 199,
    language: "Tiếng Ahh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Khác biệt trong bán hàng không phải là làm thế nào để trở nên độc nhất mà là phải trở nên khác biệt.\r\n\r\nTrong thế giới kinh doanh khốc liệt với hàng tá đối thủ cạnh tranh, làm thế nào để nhân viên bán hàng và công ty của bạn có thể trở nên khác biệt và nắm chắc phần thắng trong tay. \r\n\r\nBạn sẽ phải hạ giá sản phẩm hay dịch vụ của mình ư? \r\n\r\nBạn sẽ phải chiều theo ý muốn của khách hàng và không thể làm chủ được cuộc giao dịch này?\r\n\r\n Hay ngược lại bạn có thể định hình tiêu chí quyết định của người mua, trở nên khác biệt chứ không phải độc nhất? \r\n\r\nĐiểm khác biệt đầy sức hấp dẫn chính là BẠN…\r\n\r\nHãy biến điều đó trở nên vô giá.\r\n\r\nVà “Đừng bán hàng – Bán sự khác biệt” sẽ cho bạn thấy 19 tuyệt chiêu chốt sale khiến khách hàng không thể chối từ.\r\n\r\nGiá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 829,
    status: false,
    createdDate: "2022-11-16T17:27:03",
    updatedDate: "2022-11-16T17:27:03",
    name: "Phong cách quản lý và giữ chân nhân tài của người Nhật",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/6b/25/41/7c13046564f7f0ace99c6589605bfd01.jpg",
    price: 250000.0,
    dimension: "25 x 30 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Ngoại Ngữ ",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Phong Cách Quản Lý Và Giữ Chân Nhân Tài Của Người Nhật \r\n\r\n“Phong cách quản lý và giữ chân nhân tài của người Nhật” là một cuốn sách hướng đến đối tượng độc giả là những người đang đảm nhiệm vị trí lãnh đạo, quản lý cũng như những người sắp trở thành nhà lãnh đạo.\r\n\r\nCuốn sách bao gồm 60 nội dung thảo luận chuyên đạo cần chú tâm tìm hiểu sâu, tổng kết tất cả những chủ đề chính mà một nhà lãnh đạo trong hành trình dẫn dắt nhân sự cũng như điều hành doanh nghiệp. Không chỉ cung cấp thông tin hữu ích để người đọc trở thành một nhà lãnh đạo sáng suốt, giúp độc giả xây dựng được những tư tưởng mang tính cá nhân, mà tác giả Sugiura còn truyền động lực để thúc giục người đọc thật sự hành động thông qua những lời khuyên và các bước áp dụng cụ thể.\r\n\r\nKhông giống như nhiều cuốn sách khác có cùng chủ đề, nhưng chỉ dừng lại ở lý thuyết khái quát, “Phong cách quản lý và giữ chân nhân tài của người Nhật” có ba đặc điểm chính khác biệt sau:\r\n\r\nCác chủ đề được bàn luận đều tập trung vào hành động, để nhấn mạnh tầm quan trọng của thực tiễn, hay khả năng áp dụng các phương pháp giải quyết vấn đề vào tình huống thực tế.\r\n\r\nCuốn sách cung cấp nhiều biểu đồ minh họa để trực quan hóa lý thuyết, giúp độc giả nhanh chóng nắm bắt được các điểm then chốt",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 532,
    status: false,
    createdDate: "2022-11-16T17:27:01",
    updatedDate: "2022-11-16T17:27:01",
    name: "Work-life balance: Khi người trẻ cần cảm hứng và kế hoạch để theo đuổi sự nghiệp",
    avatar:
      "https://lzd-img-global.slatic.net/g/p/575c9f97b4ca53b7846b761ea6b74417.png_1200x1200q80.jpg_.webp",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Work-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.\r\n\r\nKhông chỉ phù hợp với những doanh nhân và lãnh đạo cấp cao, bộ công cụ có trong tác phẩm “Work-Life Balance” khả dụng với tất cả mọi người, đặc biệt là với những bạn trẻ - những người luôn cần cảm hứng và một kế hoạch sáng suốt để theo đuổi sự nghiệp.\r\n\r\nVề tác giả: Randi Zuckerberg là doanh nhân, nhà văn, người có tiếng nói trong giới công nghệ. Cô là cựu giám đốc phát triển thị trường và phát ngôn viên của Facebook, chị gái của CEO Facebook Mark Zuckerberg. Randi thường xuyên được mời diễn thuyết về công nghệ, kinh doanh và nữ quyền trong kinh doanh trên khắp thế giới.\r\n\r\nMã hàng\t8936066686082\r\nTên Nhà Cung Cấp\t1980 Books\r\nTác giả\tRandi Zuckerberg\r\nNgười Dịch\tMinh Nga Feehily\r\nNXB\tNXB Lao Động\r\nNăm XB\t2018\r\nTrọng lượng (gr)\t380\r\nKích Thước Bao Bì\t13 x 20\r\nSố trang\t360\r\nHình thức\tBìa Mềm\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Kỹ năng sống bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nWork-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
];
