/*SERVER*/
export const SERVER_LINK = "http://book.koyomiku39.moe:8080";
//http://book.koyomiku39.moe:8080
/*PATH*/
export const LOGIN_PATH = "/login";
export const REGISTER_PATH = "/register";
export const HOME_PATH = "/";
export const PROFILE_PATH = "/me";
export const BOOK_PATH = "/book";
export const CART_PATH = "/cart";
export const SKILL_BOOK_PATH = "";
export const BUSINESS_BOOK_PATH = "";
export const LITERATURE_BOOK_PATH = "";
export const KIDS_BOOK_PATH = "";
export const CULTURE_BOOK_PATH = "";
export const FAMILY_BOOK_PATH = "";
export const TEXT_BOOK_PATH = "";
export const SEARCH_PATH = "/search";

/*BREADCRUMB NAME MAP*/

export const BREADCRUMB_NAME_MAPPING = {
  [HOME_PATH]: "home",
  [PROFILE_PATH]: "profile",
  [BOOK_PATH]: "book",
  [CART_PATH]: "cart",
};

/*AVATAR SIZE*/

export const AVATAR_SIZE = {
  small: 50,
  large: 150,
};

/*HIDEN_PASSWORD */
export const HIDEN_PASSWORD = "********";

/*CARD_DUMMY_DATA*/
export const SKILL_BOOKS = [
  {
    id: 252,
    status: false,
    createdDate: "2022-11-21T22:47:49",
    updatedDate: "2022-11-21T22:47:49",
    name: " Bảy Thói Quen Của Người Thành Đạt ",
    avatar:
      "http://static.ybox.vn/2017/8/30/b04eb9ac-8d6a-11e7-a672-56c566ee3692.png",
    price: 350000.0,
    dimension: "22 x 35 cm",
    format: "Bìa cứng",
    totalPage: 299,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 19,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Quyển sách này vẫn luôn là một trong những cây đại thụ của lĩnh vực phát triển bản thân. Hàng triệu người đã thay đổi cuộc sống của mình nhờ ứng dụng các nguyên tắc trong quyển sách. Trong hàng hà sa số các quyển sách viết về những chiến lược, cách thức, chiêu trò để thành công thì quyển sách này lại đề cập đến nguyên tắc đi từ trong ra ngoài, nâng cao nội lực trước khi thành thục chiêu thức. Đây là một quyển sách cần phải đọc của bất kỳ một người thành công nào.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 253,
    status: false,
    createdDate: "2022-11-21T22:47:50",
    updatedDate: "2022-11-21T22:47:50",
    name: " Những Nguyên Tắc Thành Công",
    avatar:
      "http://static.ybox.vn/2017/8/30/ba0aae2e-8d6a-11e7-bf4b-cac091044fd5.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Rất nhiều nguyên tắc thành công được liệt kê trong quyển sách này. Bạn có thể không cần phải thực hành hết tất cả mọi nguyên tắc, nhưng mỗi nguyên tắc trong đây đều là những nguyên tắc được đúc kết từ rất nhiều người thành công trên thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 137,
    status: true,
    createdDate: "2021-03-27T15:55:05",
    updatedDate: "2021-04-06T22:28:22",
    name: "Bộ sách Brian Tracy - Nghệ thuật phát triển bản thân ",
    avatar:
      "https://static-shop.waka.vn/resize/340x497x7/image/img.product/0/0/0/7/3650_1.jpg",
    price: 560000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 220,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 12,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Với cuốn sách Nghệ thuật phát triển bản thân, Dan Strutzel và Bryan Tracy sẽ bàn về cách phát triển bản thân thông qua những kỹ năng tạo ảnh hưởng, từ đó giúp bạn tạo ra những kết quả đáng kinh ngạc như mối quan hệ cá nhân hạnh phúc hơn, bán hàng tốt hơn, tạo ra những mối quan hệ đối tác có lợi hơn cũng như hoàn thành những mục tiêu quan trọng nhất đối với bạn. Không chỉ dừng lại ở đó, cuốn sách còn giúp bạn thấy rằng thật sự có khoa học về tầm ảnh hưởng, một cơ sở khoa học đã được kiểm định và chứng minh nhiền lần, không phải chỉ trong vài năm hay vài thập kỉ, mà cả nghìn năm nay. Mục tiêu của cuốn sách này là mang đến cho bạn thật nhiều sự thật đã được kiểm chứng về tầm ảnh hưởng, loại bỏ những lời đồn đoán cũng như mớ lý thuyết nửa mùa, và đem đến cho bạn một kho tàng ý tưởng để có thể trở thành nguồn cảm hứng trong chính cuộc đời mình cũng như cuộc đời của những người mà bạn quan tâm.\r\nGiá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: "bo-sach-brian-tracy-nghe-thuat-phat-trien-ban-than-1619854016765",
    file: null,
    files: null,
    starAvg: 3,
    numberOfSearchBook: 13,
  },
  {
    id: 255,
    status: false,
    createdDate: "2022-11-21T22:47:51",
    updatedDate: "2022-11-21T22:47:51",
    name: "Làm Chủ Tư Duy, Thay Đổi Vận Mệnh",
    avatar:
      "http://static.ybox.vn/2017/8/30/cb124b32-8d6a-11e7-99ed-2e995a9a3302.jpg",
    price: 450000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 20,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Nếu bạn muốn tìm hiểu về Lập Trình Ngôn Ngữ Tư Duy (NLP) thì đây là quyển sách cực kỳ súc tích, dễ hiểu nhưng lại rất đầy đủ. Đây là quyển sách đúc kết kinh nghiệm và chiến lược thành công của diễn giả Adam Khoo – một trong những triệu phú trước tuổi 30 của Singapore.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 1273,
    status: false,
    createdDate: "2022-11-21T22:47:52",
    updatedDate: "2022-11-21T22:47:52",
    name: "Nghĩ Giàu Làm Giàu",
    avatar:
      "http://static.ybox.vn/2017/8/30/d360de3e-8d6a-11e7-ae9f-56c566ee3692.jpg",
    price: 560000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 220,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 22,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Quyển sách kinh điển này là sách gối đầu giường của rất nhiều người thành công trên thế giới. Thậm chí công ty Trung Nguyên của doanh nhân tài ba Đặng Lê Nguyên Vũ đã từng có chiến dịch phát miễn phí quyển sách này cho những bạn trẻ muốn khởi nghiệp. Đây là một quyển sách đáng để đọc và nghiền ngẫm thật nhiều lần.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 254,
    status: false,
    createdDate: "2022-11-21T22:47:51",
    updatedDate: "2022-11-21T22:47:51",
    name: "Người Dám Cho Đi",
    avatar:
      "http://static.ybox.vn/2017/8/30/c240c5c4-8d6a-11e7-afaf-56c566ee3692.jpg",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Nếu bạn muốn nâng cao giá trị của bạn, tăng thu nhập, tăng sự ảnh hưởng của mình thì đây chính là quyển sách dành cho bạn. Nguyên tắc trong quyển sách này rất đơn giản, nhưng lại cực kỳ mạnh mẽ và hữu dụng.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 132,
    status: true,
    createdDate: "2021-03-27T15:39:13",
    updatedDate: "2022-11-16T21:06:48",
    name: "Trang Tử tâm đắc (Tái bản)",
    avatar: "https://cf.shopee.vn/file/71d30d277fab71cfe30056dc81eb4e54",
    price: 450000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 10,
    hot: true,
    act: false,
    buyCount: 0,
    desc: "Mọi người đều biết, Trang Tử là người có tâm hồn không nhuốm hồng trần, không luỵ thế tục, tự do tự tại, biết giũ bỏ mọi vật tục, tạp niệm để cho tâm hồn mìnhgiao hòa cùng tinh thần trời đất. Trên đến tận trời xanh, dưới đến tận suối vàng, khi vui thì ông cười, khi giận thì ông mắng, kiến giải sâu sắc, luận khắp anh hùng trong thiên hạ.\r\n\r\nChúng ta biết rất ít về cuộc đời Trang Tử. Ghi chép chính xác về cuộc đời ông chỉ là vài dòng ngắn gọn trong sách Sử ký của Tư Mã Thiên: Trang Tử là người đất Mông thuộc nước Tống thời Chiến Quốc (nay thuộc huyện Thương Khâu, tỉnh Hà Nam). Ông từng giữ chức Tất Viên tiểu lại, tương đương với chức thủ kho ngày nay. Cả đời ông sống trong thời Chiến Quốc phân tranh, chiến loạn liên miên, khắp nơi cầu hiền như khát nước. Nhưng ông ẩn cư đến già, không chịu ra làm quan, không có bất kỳ một danh phận xã hội nào. Ông chỉ để lại một cuốn Trang Tử (hay còn gọi là Nam Hoa kinh) xưa nay được liệt vào hàng kinh điển. Giá trị của nó chính là ở tư tưởng vô biên vô cùng, kỳ dị mà độc đáo.",
    slug: "trang-tu-tam-dac-tai-ban-1619853957367",
    file: null,
    files: null,
    starAvg: 5,
    numberOfSearchBook: 20,
  },
  {
    id: 134,
    status: true,
    createdDate: "2021-03-27T15:47:09",
    updatedDate: "2021-03-27T16:00:22",
    name: "Trí tuệ cộng tác",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/19/1e/ed/a54f09671673fcdfe924e7bf854a680f.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Hãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?\r\n\r\nCUỐN SÁCH MANG LẠI CHO BẠN ĐIỀU GÌ\r\n\r\nMột phần tâm trí của chúng ta là sự giao thoa với những tâm trí khác. Khi mất đi sự hợp tác, con người mất đi sự gắn kết bề sâu của các mối quan hệ\r\n\r\nTâm trí của mỗi người đều có cách vận hành của riêng nó và chúng ta bất đồng quan điểm vì chúng ta không hiểu mình và không hiểu nhau, không biết cách suy nghĩ của mình và cách suy nghĩ của nhau\r\n\r\nTất cả những gì còn lại liên quan đến thế giới xung quanh chỉ là sự mù mờ, sự mơ hồ. Dù cánh cửa tư duy có đang đóng chặt, dù cánh cửa kết nối có đang khóa kín, chắc chắn sẽ có cách mở ra. Chẳng đâu xa, cuốn sách này chính là:\r\n\r\n•          Tấm bản đồ chi tiết về dạng thức tâm trí của bạn\r\n\r\n•          Chìa khóa giúp bạn đột phá ý tưởng nhờ định hướng mục tiêu\r\n\r\n•          Chỉ dẫn giúp bạn thay đổi và thiết lập trật tự cho cuộc sống\r\n\r\nTrí tuệ cộng tác sẽ đưa bạn từ quá khứ đến với tương lai, đó là một con đường dài, cần có người chung vai giúp sức. Việc chúng ta khác nhau không có nghĩa là phải có một người trong chúng ta là người sai. Điều đó đơn giản là không chỉ có một cách để đúng\r\n\r\nBởi vì câu hỏi thực sự cần đặt ra không phải là từng người có biểu hiện tốt đến đâu, mà là chúng ta có thể cùng nhau cộng tác làm việc hiệu quả tới mức nào\r\n\r\nThất bại và đổ vỡ đều bắt nguồn từ những lối mòn trong tư duy. Và đột phá bắt nguồn từ những suy nghĩ vượt ra khỏi các giới hạn của thói quen thông thường\r\n\r\nGiới hạn trong tư duy chắc chắn sẽ giới hạn con đường đi đến thành công của bạn. Cuốn sách này sẽ giúp bạn mở ra cánh cửa tâm trí đang bị đóng chặt, giúp bạn kết nối với thế giới xung quanh và HÒA NHỊP TƯ DUY, PHÁT HUY SỨC MẠNH ĐỘT PHÁ\r\n\r\nTHÔNG TIN TÁC GIẢ\r\n\r\nDAWNA MARKOVA, Ph.D\r\n\r\nCEO Danh dự của Tổ chức Professional Thinking PartnersTM .\r\n\r\nTiến sĩ Dawna Markova là một chuyên gia nổi tiếng quốc tế trong các lĩnh vực trị liệu tâm lí, nghiên cứu nhận thức và năng lực con người.\r\n\r\nTiến sĩ Markova là cựu thành viên cao cấp của Trung tâm Tổ chức Học tập (Organizational Learning Center) tại MIT và là thành viên tư vấn của Hiệp hội Tổ chức Học tập (Society for Organizational Learning). Bà đã thành lập các cộng đồng nghiên cứu trên khắp Hoa Kỳ, lãnh đạo các hội thảo về tối đa hóa tài năng cá nhân và đội nhóm, đóng vai trò là đối tác tư duy cho các CEO và giám đốc điều hành cấp cao trên toàn thế giới.\r\n\r\nTác phẩm:\r\n\r\nI Will Not Die an Unlived Life: Reclaiming Purpose and Passion (2000)\r\n\r\nRandom Acts of Kindness Series (2002)\r\n\r\nA Spot of Grace: Remarkable Stories Of How You DO Make a Difference (2008)\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting In a Disconnected World (2017) – đồng tác giả\r\n\r\nANGIE MCARTHUR​​​​​​​\r\n\r\nCEO của Tổ chức Professional Thinking PartnersTM (từ năm 1998 đến nay)\r\n\r\nCô là một chuyên gia nghiên cứu mô hình nhận thức nhận thức và phát triển các chiến lược truyền thông cho các nhà lãnh đạo và đội nhóm, từ các tổ chức từ phi lợi nhuận cho đến các công ty thuộc top 500 do tạp chí Fortune bình chọn.\r\n\r\nCô cũng là một trong những người tạo ra Mạng lưới Phụ nữ Toàn cầu (Worldwide Women’s Web) – thành lập năm 2001 nhằm kết nối các nữ lãnh đạo doanh nghiệp trên thế giới.\r\n\r\nTác phẩm:\r\n\r\nTrí tuệ Cộng tác (Collaborative Intelligence: Thinking with People Who Think Differently, 2015) – đồng tác giả\r\n\r\nReconcilable Differences: Connecting in a Disconnected World (2017) – đồng tác giả.\r\n\r\nMã hàng\t9786045680513\r\nTên Nhà Cung Cấp\tBách Việt\r\nTác giả\tDawna Markova, PhD, Angie McArthur\r\nNgười Dịch\tNguyễn Nguyên Khôi\r\nNXB\tNXB Phụ Nữ Việt Nam\r\nNăm XB\t2020\r\nTrọng lượng (gr)\t530\r\nKích Thước Bao Bì\t20 x 13.5 cm\r\nSố trang\t528\r\nHình thức\tBìa Mềm\r\nSản phẩm hiển thị trong\t\r\nBách Việt\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Tâm lý bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nTRÍ TUỆ CỘNG TÁC - Collabrotive Intelligence\r\n\r\nHãy nghĩ về những điều đúng lớn\r\n\r\nBên trong mỗi người luôn ẩn giấu một hạt giống của sự xuất sắc, đang chờ đợi không gì hơn ngoài sự chăm chút và tưới tắm để nảy mầm vươn nắng, để chiến thắng chính mình\r\n\r\nSức mạnh ẩn giấu trong mỗi chúng ta có thể trở nên vô cùng mạnh mẽ, mạnh mẽ hơn bất cứ thử thách nào chúng ta phải đối mặt. Thậm chí, nó có khả năng giải phóng chúng ta khỏi mọi khổ đau, phiền não mà chúng ta phải chịu đựng bấy lâu nay\r\n\r\nNăng lực sáng tạo, chia sẻ và thực hành ý tưởng là thứ tài sản quý giá nhất mà chúng ta có. Bạn có nhận ra không?",
    slug: "tri-tue-cong-tac-1619853982481",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 13,
  },
  {
    id: 135,
    status: true,
    createdDate: "2021-03-27T15:48:34",
    updatedDate: null,
    name: "Work-life balance: Khi người trẻ cần cảm hứng và kế hoạch để theo đuổi sự nghiệp",
    avatar:
      "https://lzd-img-global.slatic.net/g/p/575c9f97b4ca53b7846b761ea6b74417.png_1200x1200q80.jpg_.webp",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 8,
    hot: false,
    act: true,
    buyCount: 1,
    desc: "Work-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.\r\n\r\nKhông chỉ phù hợp với những doanh nhân và lãnh đạo cấp cao, bộ công cụ có trong tác phẩm “Work-Life Balance” khả dụng với tất cả mọi người, đặc biệt là với những bạn trẻ - những người luôn cần cảm hứng và một kế hoạch sáng suốt để theo đuổi sự nghiệp.\r\n\r\nVề tác giả: Randi Zuckerberg là doanh nhân, nhà văn, người có tiếng nói trong giới công nghệ. Cô là cựu giám đốc phát triển thị trường và phát ngôn viên của Facebook, chị gái của CEO Facebook Mark Zuckerberg. Randi thường xuyên được mời diễn thuyết về công nghệ, kinh doanh và nữ quyền trong kinh doanh trên khắp thế giới.\r\n\r\nMã hàng\t8936066686082\r\nTên Nhà Cung Cấp\t1980 Books\r\nTác giả\tRandi Zuckerberg\r\nNgười Dịch\tMinh Nga Feehily\r\nNXB\tNXB Lao Động\r\nNăm XB\t2018\r\nTrọng lượng (gr)\t380\r\nKích Thước Bao Bì\t13 x 20\r\nSố trang\t360\r\nHình thức\tBìa Mềm\r\nSản phẩm bán chạy nhất\tTop 100 sản phẩm Kỹ năng sống bán chạy của tháng\r\nGiá sản phẩm trên Fahasa.com đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như Phụ phí đóng gói, phí vận chuyển, phụ phí hàng cồng kềnh,...\r\nWork-life Balance: Khi Người Trẻ Cần Cảm Hứng Và Kế Hoạch Để Theo Đuổi Sự Nghiệp\r\n\r\nBạn cảm thấy quay cuồng với cuộc sống? Công việc. Gia đình. Giấc ngủ. Bạn bè... - tất cả đều quan trọng với bạn và bạn chẳng thể tìm đủ chỗ cho chúng trong 24 tiếng đồng hồ ít ỏi! Xin chào, bạn không phải là người duy nhất gặp khó khăn.\r\n\r\nChúng ta đều có những lúc căng thẳng và mệt mỏi vì không thể cân bằng công việc với cuộc sống, đến mức cảm thấy tội lỗi nếu lỡ không hoàn thành được một việc gì đó trong danh sách những điều cần ưu tiên. Cuốn sách thông minh, tinh tế và đầy tâm lý của Randi Zuckerberg sẽ phá vỡ quan điểm không đáng có này!\r\n\r\nBằng cách cung cấp phương pháp Bộ Ba Lựa Chọn và những lời khuyên đầy thực tiễn, Randi đặt vào tay người đọc bí quyết để sống cuộc đời tươi đẹp nhất, sắp xếp cuộc sống thật hiệu quả. Thông qua nhiều câu chuyện quản lý cuộc sống của những chuyên gia tại các công ty hàng đầu thuộc thung lũng Silicon, của những người mẹ mong muốn dành thêm thời gian cho gia đình, của những sinh viên mới ra trường luôn cố gắng kiểm soát mọi thứ..., Randi đã truyền tải thông điệp: Đừng mong chờ sự cân bằng hoàn hảo, mà thay vì thế, hãy dám lựa chọn, gạt bỏ những kỳ vọng vô lý và tận hưởng những điều bạn thật sự trân trọng.",
    slug: "work-life-balance-khi-nguoi-tre-can-cam-hung-va-ke-hoach-de-theo-duoi-su-nghiep-1619853989257",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 13,
  },
  {
    id: 251,
    status: false,
    createdDate: "2022-11-21T22:47:49",
    updatedDate: "2022-11-21T22:47:49",
    name: "Đánh Thức Con Người Phi Thường Trong Bạn",
    avatar:
      "http://static.ybox.vn/2017/8/30/a3cb4f7e-8d6a-11e7-8572-2e995a9a3302.jpg",
    price: 450000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: false,
    buyCount: 0,
    desc: "Anthony Robbins là một trong những diễn giả, chuyên12 gia đào tạo bậc thầy của thế giới. Trong hơn 3 thập kỷ làm đào tạo của ông, ông chỉ viết hai quyển sách và quyển sách này là một trong những quyển sách có tầm ảnh hưởng rất lớn trong lĩnh vực phát triển bản thân. Sách đề cập đến gần như mọi lĩnh vực quan trọng trong cuộc sống và các cách thức làm thế nào để đạt được thành công trong lĩnh vực đó.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
];

export const DETECTIVE_BOOKS = [
  {
    id: 1232,
    status: false,
    createdDate: "2022-11-21T22:47:51",
    updatedDate: "2022-11-21T22:47:51",
    name: " Án mạng trên sông Nile",
    avatar:
      "https://simg.zalopay.com.vn/zlp-website/assets/Sach_trinh_tham_An_mang_tren_song_Nile_153254ff19.jpg",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Án mạng trên sông Nile là một cuốn tiểu thuyết trinh thám, hình sự được nhà văn Agatha Christie phát hành vào ngày 1/11/1937. Nội dung chính của tác phẩm là một vụ án mạng xảy ra tại một con tàu du lịch trên sông Nile trong hành trình đến Ai Cập.  \n\nLinnet Ridgeway là một thiếu nữ có trong tay tất cả mọi thứ từ nhan sắc đến của cải. Được cô bạn thân Jacqueline nhờ vả, Linnet đã sắp xếp cho Simon - vị hôn thê của Jacqueline vào làm việc tại điền trang của cô. Nhưng trớ trêu thay, sau khi Simon bắt đầu làm việc tại đây, anh và Linnet lại phải lòng nhau. Hai người tiến tới hôn nhân trước sự ngỡ ngàng của Jacqueline. Vì quá đau đớn và uất hận khi bị 2 người mình tin tưởng nhất phản bội, Jacqueline quyết tâm phải trả thù cặp đôi này bằng mọi giá. Đó cũng là lý do vì sao cả 3 người cùng xuất hiện trên con tàu du lịch trên sông Nile. Mọi chuyện trở nên rối loạn khi cô hầu gái của Linnet phát hiện cô chủ của mình đã bị giết chết. Không lâu sau đó, cô hầu gái cũng được phát hiện là đã thiệt mạng. Liệu ai là người đứng sau những vụ giết người bí ẩn này? ",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 1279,
    status: false,
    createdDate: "2022-11-21T22:47:52",
    updatedDate: "2022-11-21T22:47:52",
    name: " Phía sau Nghi can X - Higashino Keigo",
    avatar:
      "https://simg.zalopay.com.vn/zlp-website/assets/Sach_trinh_tham_Phia_sau_nghi_can_x_b40006ec49.jpg",
    price: 560000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 220,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 22,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Phía sau nghi can X là một trong những cuốn sách trinh thám hay nhất của tác giả Higashino Keigo. Togashi và Yasuki là một đôi vợ chồng đã ly hôn với nhau 5 năm. Sự trở lại đột ngột của Togashi sau 5 năm đã khiến mọi chuyện trở nên hỗn loạn. Sau một hồi giằng co, Yasuki đã vô tình giết hại chồng cũ. Hàng xóm của Yasuki - Ishigami đã đề nghị giúp đỡ cô xử lý cái xác và dàn xếp mọi chuyện ổn thỏa. Điều tra viên Kusanagi và phó giáo sư vật lý Manabu Yukawa đã cùng nhau phối hợp điều tra vụ án mạng này. Cuốn sách trinh thám này đã công khai hung thủ và đồng phạm ngay từ những giây phút đầu tiên nhưng dưới ngòi bút của Keigo, cuốn tiểu thuyết vẫn khiến người bị cuốn theo những giây phút tìm kiếm sự thật về cách mà một thiên tài toán học - Ishigami gây án. Đây không chỉ đơn thuần là một cuốn sách trinh thám với những yếu tố kịch tính, gay cấn, và tình tiết gây án đầy logic mà còn ẩn chứa cả là tình yêu đầy đau đớn mà Ishigami dành cho Yasuki.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 1182,
    status: false,
    createdDate: "2022-11-21T22:47:50",
    updatedDate: "2022-11-21T22:47:50",
    name: " Sherlock Holmes",
    avatar:
      "https://simg.zalopay.com.vn/zlp-website/assets/Sach_trinh_tham_Sherlock_Holmes_6ae8e27e2f.jpg",
    price: 350000.0,
    dimension: "22 x 35 cm",
    format: "Bìa cứng",
    totalPage: 299,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 19,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Sherlock Holmes là một tác phẩm kinh điển thuộc thể loại trinh thám nổi danh trên khắp thế giới. Tuy chỉ là một nhân vật hư cấu, nhưng Sherlock Holmes đã trở thành nguồn cảm hứng cho nhiều tác phẩm ở nhiều loại hình nghệ thuật khác nhau như nhạc kịch, điện ảnh,... Tác phẩm không chứa đựng những tình tiết giật gân hay giết người tàn nhẫn, nhưng vẫn thu hút đông đảo độc giả bởi những tình tiết logic, sáng tạo cùng với cuộc đấu trí cân não giữa thám tử Sherlock Holmes và giáo sư Moriarty.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 1256,
    status: false,
    createdDate: "2022-11-21T22:47:51",
    updatedDate: "2022-11-21T22:47:51",
    name: "Án mạng trên chuyến tàu tốc hành Phương Đông - Agatha Christie",
    avatar:
      "https://simg.zalopay.com.vn/zlp-website/assets/Sach_trinh_tham_An_mang_tren_chuyen_tau_toc_hanh_phuong_Dong_0319c16b51.jpg",
    price: 450000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 20,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Án mạng trên chuyến tàu tốc hành phương Đông là một cuốn sách trinh thám kinh điển khác của tác giả nổi tiếng thế giới - Agatha Christie. Nội dung cuốn sách kể về một vụ án mạng bí ẩn xảy ra trên chuyến tàu tốc hành Phương Đông theo lộ trình từ Istanbul về Calais. Và thật tình cờ, thám tử Hercule Poirot cũng có mặt trên chuyến tàu này. Khoang tàu được khóa kín từ bên trong và nạn nhân bị đâm đến 12 nhát dao. Tuy nhiên, 12 nhát dao này lại không phải của cùng 1 hung thủ. Sau khi khám xét hành lý và thẩm vấn từng người, thám tử Hercule phát hiện ra rằng có đến 12 người là nghi phạm trong vụ án hóc búa này. Vậy ai mới là kẻ gây án thật sự?",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 1300,
    status: false,
    createdDate: "2022-11-21T22:47:53",
    updatedDate: "2022-11-21T22:47:53",
    name: "Hỏa ngục - Dan Brown",
    avatar:
      "https://simg.zalopay.com.vn/zlp-website/assets/Sach_trinh_tham_Hoa_nguc_bf5867e304.jpg",
    price: 200000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 400,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Nhắc đến những cuốn tiểu thuyết trinh thám nổi tiếng trên thế giới, chắc chắn chúng ta không thể bỏ qua một tác phẩm cực kì nổi tiếng là Hỏa Ngục của nhà văn người Mỹ - Dan Brown. Tác phẩm được xuất bản vào năm 2013 và ngay lập tức trở thành một trong những cuốn tiểu thuyết bán chạy nhất trên danh sách New York Times Best Seller.\n\nTrong tác phẩm này, Robert Langdon bị mắc kẹt trong một chuỗi mật mã bí ẩn, được sáng tạo bởi một nhà khoa học xuất chúng. Nhà khoa học này có một nỗi ám ảnh đáng sợ về sự diệt vong và gia tăng dân số. Vì thế, ông đã tạo ra một loại virus có thể làm lây lan dịch bệnh gây chết người và giấu nó ở một nơi bí mật. Hỏa Ngục là hành trình Langdon đi qua các địa điểm trên thế giới để cố gắng tìm ra loại virus nguy hiểm và cứu thế giới khỏi sự diệt vong.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 1157,
    status: false,
    createdDate: "2022-11-21T22:47:49",
    updatedDate: "2022-11-21T22:47:49",
    name: "Mật mã Da Vinci ",
    avatar:
      "https://simg.zalopay.com.vn/zlp-website/assets/Sach_trinh_tham_Mat_ma_Da_Vinci_75274bd227.jpg",
    price: 450000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: false,
    buyCount: 0,
    desc: "Nhắc đến những cuốn sách trinh thám hay nhất mọi thời đại, không thể không đề cập đến tác phẩm Mật mã Da Vinci - một cuốn tiểu thuyết nổi tiếng của tác giả Dan Brown. Cuốn sách gây ấn tượng mạnh với nhiều độc giả bởi sự pha trộn giữa 2 yếu tố trinh thám và thần thoại. Cốt truyện kể về hành trình truy tìm địa điểm cất giấu Chén Thánh của Robert Langdon - một giáo sư đang giảng dạy tại Harvard và Sophie Neveu - một chuyên viên giải mã đang làm việc trong lực lượng cảnh sát Pháp thông qua một vụ giết người. Với những tình tiết hấp dẫn, kịch tính, chân thực, tác phẩm này sẽ đưa bạn đi từ bất ngờ này đến bất ngờ khác, khiến độc giả không thể rời mắt cho đến những trang sách cuối cùng. ",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 151,
    status: true,
    createdDate: "2021-04-17T16:41:58",
    updatedDate: null,
    name: "RATMAN - Bản sao chép lỗi",
    avatar:
      "https://salt.tikicdn.com/ts/product/db/45/34/37c013ef9f24a34f6ac022df8360dd11.jpg",
    price: 350000.0,
    dimension: "25 x 30 cm",
    format: "Bìa mềm",
    totalPage: 450,
    language: "Tiếng Việt",
    publicationDate: "2021-04-17T00:00:00",
    discount: 10,
    hot: false,
    act: true,
    buyCount: 1,
    desc: "Hai cái chết – dưới một góc nhìn.\r\n\r\nHai bí ẩn – vẫn chưa được lý giải.\r\n\r\nCái chết của người chị gái khi Himekawa còn nhỏ, và cái chết của người yêu ở thời điểm hiện tại. Chỉ là tai nạn hay đã bị sát hại? Quá khứ và hiện tại đan xen nhau, như được lồng ghép vào nhau dưới góc nhìn, suy nghĩ và nỗi lòng nhân vật. Có những sự thật bị cái nhìn chủ quan che lấp, giống như nghệ thuật đánh lừa nổi tiếng Ratman.\r\n\r\nNhững nghi phạm đã được chỉ định, hiện trường đã được mô tả, tất cả đều được tác giả bày sẵn để đợi độc giả lý giải.\r\n\r\nTrong bức tranh Ratman, thứ ta thấy là ông già hay là con chuột? Còn trong vụ án này, hãy cẩn thận đừng để bị định kiến đánh lừa!\r\n\r\nĐây là một bộ tiểu thuyết trinh thám về nghệ thuật đánh lừa tâm ký do định kiến, đã bán hơn 128.000 bản tại Nhật, xếp thứ 10 giải thưởng văn học KONOMYS năm 2008 và được đề cử giải thưởng YAMAMOTO SHUGORO năm 2009.",
    slug: "ratman-ban-sao-chep-loi-1619854149501",
    file: null,
    files: null,
    starAvg: 5,
    numberOfSearchBook: 13,
  },
  {
    id: 1207,
    status: false,
    createdDate: "2022-11-21T22:47:50",
    updatedDate: "2022-11-21T22:47:50",
    name: "Sự im lặng của bầy cừu",
    avatar:
      "https://simg.zalopay.com.vn/zlp-website/assets/Sach_trinh_tham_Su_im_lang_cua_bay_cuu_48932b9722.jpg",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Sự im lặng của bầy cừu được xuất bản vào năm 1988, là phần tiếp theo của cuốn tiểu thuyết Rồng đỏ phát hành năm 1981. Nội dung tác phẩm kể về Tiến sĩ Hannibal Lecter - một kẻ giết người hàng loạt và ăn thịt người. Clarice Starling, một nhân viên thực tập của FBI được phân công thu thập thông tin từ Lecter nhằm điều tra về một kẻ giết người hàng loạt bí ẩn - “Buffalo Bill”. Cuộc đối đầu giữa Clarice và Hannibal đạt đến đỉnh điểm khi con gái của một Thượng nghị sĩ bị bắt cóc. Những cuộc đấu trí căng thẳng, những màn giết người ám ảnh, Sự im lặng của bầy cừu hội tụ đầy đủ các yếu tố của một cuốn tiểu thuyết trinh thám hay nhất mọi thời đại.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 152,
    status: true,
    createdDate: "2021-04-17T16:33:10",
    updatedDate: null,
    name: "Tiểu Thuyết Trinh Thám 1/14 ",
    avatar:
      "https://salt.tikicdn.com/cache/w1200/ts/product/8b/95/af/f405d953b508fe89c314f9fdd99911bd.jpg",
    price: 280000.0,
    dimension: "25 x 30 cm",
    format: "Bìa cứng",
    totalPage: 290,
    language: "Tiếng Việt",
    publicationDate: "2021-04-17T00:00:00",
    discount: 8,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "1/14 là một trò chơi kì lạ. Đây là một trò chơi thử thách trí tuệ và lòng dũng cảm, người thắng cuộc sẽ giành được phần thưởng vô cùng lớn và quyền được sinh tồn, còn những kẻ vi phạm nguyên tắc trò chơi sẽ phải nhận sự trừng phạt chính là cái chết.\r\n\r\nMười bốn tác giả chuyên viết tiểu thuyết trinh thám bị “mời” đến một nơi bí mật, những tình huống kì lạ xảy ra, những sự kiện đáng sợ và bất ngờ liên tục xuất hiện, khiến họ không tài nào lí giải nổi. Cái chết luôn rình rập mọi lúc, mọi nơi, không khí căng thẳng bao trùm. Khi số người sống sót càng ngày càng ít, họ dần nhận ra một “quy luật” và bí mật kinh người…\r\n\r\n“Trò chơi tử thần” đã bắt đầu, kẻ chủ mưu vẫn lẩn khuất xung quanh họ là ai? Hắn ta? Cô ta? Rốt cục có mục đích gì? Sau mười bốn ngày, có ai còn sống sót và thoát khỏi nơi quỉ quái đó hay không? Liệu sau đó còn có điều gì đáng sợ hơn chăng? Đó lẽ nào là một trò chơi không bao giờ kết thúc?\r\n\r\nHãy nhớ rằng, kể từ khi mở trang đầu tiên, bạn đã trở thành một nhân vật trong trò chơi đó!\r\n\r\nGiá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
    slug: "tieu-thuyet-trinh-tham-1-14-1619854149520",
    file: null,
    files: null,
    starAvg: 5,
    numberOfSearchBook: 13,
  },
  {
    id: 148,
    status: true,
    createdDate: "2021-03-27T17:52:54",
    updatedDate: null,
    name: "Trò chơi của Ripley",
    avatar:
      "https://nhasachphuongnam.com/images/detailed/176/tro-choi-cua-ripley.jpg",
    price: 500000.0,
    dimension: "20 x 10 cm",
    format: "Bìa cứng",
    totalPage: 2000,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 15,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Tom Ripley chỉ quan tâm đến tiền.\r\n\r\nTom Ripley chỉ giết người vô tội.\r\n\r\nTom Ripley chỉ giả vờ hiền lành để người khác quý mến.\r\n\r\nThông qua phần 1 – Quý ngài tài năng và phần 2 – Thế giới ngầm của Ripley, độc giả đã hiểu rõ về quá trình mà Tom Ripley từ một thanh niên “có vẻ hiền lành” trở thành một kẻ sát nhân. Hai phần đầu dường như khiến người đọc cảm thấy đã hiểu rõ về nhân vật này.\r\n\r\nThế nhưng…\r\n\r\nMọi điều bạn nghĩ mình biết về Tom Ripley – nhân vật phản anh hùng được yêu thích nhất của Patricia Highsmith – sắp hoàn toàn thay đổi.\r\n\r\nAnh tham gia vào một phi vụ chỉ vị cảm thấy bản thân có trách nhiệm.\r\n\r\nAnh trừng trị những kẻ sát nhân.",
    slug: "tro-choi-cua-ripley-1619854047391",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 13,
  },
];

export const SCIENCE_BOOKS = [
  {
    id: 228,
    status: false,
    createdDate: "2022-11-21T22:47:53",
    updatedDate: "2022-11-21T22:47:53",
    name: " Tết hoàng cung",
    avatar: "https://book365.vn/tet-hoang-cung.png",
    price: 450000.0,
    dimension: "25 x 30 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Tết hoàng cung là tuyển tập những khám phá, nghiên cứu của tác giả Nguyễn Phước Hải Trung về không gian Tết chốn cung đình nhà Nguyễn. Cuốn sách được sắp xếp theo bốn chuyên mục: “Tết Hoàng cung Huế”, “Năm Dần nói chuyện với hổ trong văn hóa cung đình”, “Tết & mùa xuân trong thơ vua” và “Bảo vật của tinh thần dân tộc”. Mỗi chuyên mục trong sách lại tái hiện cho chúng ta một phần của không khí Tết chốn cung đình khi xưa.\nMời bạn bước vào chuyên mục “Tết Hoàng cung Huế” với những thông tin thú vị và bổ ích về các lễ nghi, truyền thống hoàng cung của triều đại gần với chúng ta nhất – nhà Nguyễn. Những nghi thức như Lễ Ban sóc, Lễ Tiến xuân ngưu, Lễ Tế Giao, trồng cây Nêu… sẽ được tái hiện một cách chi li qua ngòi bút của tác giả, giúp chúng ta hình dung một cách đầy đủ nhất về không khí ngày Tết nơi cung đình.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 225,
    status: false,
    createdDate: "2022-11-21T22:47:51",
    updatedDate: "2022-11-21T22:47:51",
    name: "500 câu hỏi Lịch sử văn hóa Việt Nam ",
    avatar: "https://book365.vn/sachvanhoc4.png",
    price: 450000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 20,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: 'Hai tác giả Hà Nguyễn và Phùng Nguyên đã thể hiện những sự kiện, văn hoá lịch sử của đất nước dưới hình thức những câu hỏi - đáp ngắn gọn - một xu hướng biên soạn sách phù hợp với độc giả ngày nay, đặc biệt là lớp trẻ lớn lên dưới ảnh hưởng của những cuốn truyện tranh kiệm lời thoại. Độc giả sẽ không mất quá nhiều thời gian tra cứu mà vẫn có thể hiểu những khái niệm, những sự kiện một cách khái quát nhất, cô đọng nhất của đất nước, dân tộc qua cuốn 500 câu Hỏi - Đáp lịch sử-văn hoá Việt Nam. \n\nSách chia làm 2 phần: Phần 1: Lịch sử-Văn hoá Việt Nam, những vấn đề chung; Phần 2: Theo dòng lịch sử - văn hoá Việt Nam. Chỉ chiếm chừng 30 trang đầu của tác phẩm nhưng phần Một nêu những vấn đề "vĩ mô" rất hấp dẫn, lý thú, chẳng hạn như: Không gian lãnh thổ Việt Nam hiện nay được giới hạn như thế nào? Dân tộc Việt Nam có nguồn gốc từ đâu? Không gian văn hoá Việt Nam hiện nay về cơ bản được xác lập như thế nào? Không gian văn hoá Việt Nam được tạo thành bởi 3 vùng văn hoá lớn. Đó là những vùng nào? Trong lịch sử Việt Nam (từ khởi thuỷ đến 1945) từng có bao nhiêu kinh đô? Sự mở rộng nước ta kéo dài về phía Nam diễn tiến trong lịch sử như thế nào?, ',
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 224,
    status: false,
    createdDate: "2022-11-21T22:47:51",
    updatedDate: "2022-11-21T22:47:51",
    name: "500 câu hỏi đáp sắc màu văn hóa Việt Nam",
    avatar: "https://book365.vn/vanhoa3.png",
    price: 280000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 240,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 18,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Các kết quả nghiên cứu trong lĩnh vực địa chí, văn hóa học và lịch sử - văn hóa Việt Nam đã đưa ra nhiều phương án nhận thức và phân loại đối với từng vùng miền văn hóa cấu thành tổng thể không gian văn hóa Việt Nam. Trong đó, phác thảo phân vùng văn hóa ở Việt Nam thành hai cấp độ là vùng văn hóa và tiểu vùng văn hóa của Giáo sư Ngô Đức Thịnh (Nguyên Viện trưởng Viện Nghiên cứu Văn hóa dân gian thuộc Viện Hàn lâm Khoa học xã hội Việt Nam) cùng các đồng nghiệp nhận được nhiều ý kiến tán đồng, nhất trí. Theo cách phân chia này, tổng thể không gian văn hóa Việt Nam thống nhất trong đa dạng, được tạo thành từ 7 vùng văn hóa (Đồng bằng Bắc Bộ, Đông Bắc Bắc Bộ, Tây Bắc và miền núi Bắc Trung Bộ, Duyên hải Bắc Trung Bộ, Duyên hải Trung và NamTrung Bộ, Trường Sơn - Tây Nguyên, Nam Bộ) và 23 tiểu vùng văn hóa (Đất Tổ - Phú Thọ, xứ Bắc, Thăng Long - Hà Nội, xứ Đông, xứ Nam, xứ Lạng, rẻo cao Việt Bắc, Tây Bắc, miền núi Thanh - Nghệ, hỗn hợp Thái - Mường, xứ Thanh, xứ Nghệ, xứ Huế, xứ Quảng, Bình Định - Phú Yên, cực nam Trung Bộ, Trường Sơn, Bắc Tây Nguyên, Trung Tây Nguyên, Nam Tây Nguyên, sông Đồng Nai, Sài Gòn - Gia Định, đồng bằng sông Cửu Long).",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 167,
    status: true,
    createdDate: "2021-05-12T11:45:49",
    updatedDate: "2021-05-12T11:45:49",
    name: "AI bước tiến đột phá trong chăm sóc sức khỏe",
    avatar:
      "https://salt.tikicdn.com/ts/product/22/de/c1/aae695d03a6ae16d9097457c9b69deb8.jpg",
    price: 350000.0,
    dimension: "25 x 30 cm",
    format: "Bìa mềm",
    totalPage: 350,
    language: "Tiếng Việt",
    publicationDate: "2021-05-12T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Eric Topol là một trong những bác sỹ giỏi nhất nước Mỹ, chuyên về lĩnh vực tim mạch, đồng thời là người đứng đầu Viện Khoa học Tịnh tiến Scripps, nguyên là Chủ tịch tim mạch của Cleveland Clinic. Ông được liệt vào top 10 nhà khoa học có những bài báo được trích dẫn nhiều nhất hiện nay.\r\n\r\nNền Y học trong thời đại chúng ta đang sống đã chạm ngưỡng báo động về sự thiếu liên kết giữa con người với nhau, cụ thể là bác sĩ với bệnh nhân.\r\n\r\nAI xuất hiện cùng với những hứa hẹn đầy triển vọng về một tương lai của ngành Y, nơi bác sĩ giao tiếp, đồng cảm, thấu hiểu với bệnh nhân bằng tất cả lòng trắc ẩn của mình.\r\n\r\nAI, một mặt, trả lại tính nhân văn sâu sắc cho Y học, đưa Y học trở thành “Deep medicine” nếu được sử dụng đúng cách ; mặt khác, nếu sử dụng sai cách thì AI sẽ dẫn Y học của chúng ta tới vực thẳm.\r\n\r\nLàm thế nào để AI đưa Y học phát triển theo đúng lộ trình, sự kết nối giữa bác sỹ và bệnh nhân ngày một thắt chặ Câu trả lời sẽ được bác sĩ hàng đầu Hoa Kỳ Eric Topol giải đáp trong Deep Medicine, AI – Bước tiến đột phá trong chăm sóc sức khỏe.",
    slug: "ai-buoc-tien-dot-pha-trong-cham-soc-suc-khoe-1620794749140",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 13,
  },
  {
    id: 223,
    status: false,
    createdDate: "2022-11-21T22:47:50",
    updatedDate: "2022-11-21T22:47:50",
    name: "Bản sắc văn hóa vùng ở Việt Nam",
    avatar: "https://book365.vn/ban-sac-van-hoa-vung.png",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Văn hóa vùng hình thành trên cơ sở giao lưu, giao tiếp lâu đời giữa các dân tộc có sự tương đồng về kinh tế, xã hội, cùng sinh sống trong một vùng địa lý nhất định, văn hóa vùng đóng vai trò như là bước trung gian, như cái cầu nối, để từ văn hóa tộc người, thai nghén và hình thành văn hóa quốc gia; và ngược lại, từ văn hóa quốc gia, tác động trở lại các xu hướng phát triển của văn hóa tộc người, văn hóa vùng. Cuốn sách 09 chương giúp ta có cái nhìn tổng quan về bản sắc văn hoá đất nước ta:",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 222,
    status: false,
    createdDate: "2022-11-21T22:47:49",
    updatedDate: "2022-11-21T22:47:49",
    name: "Combo sách Không gian Văn hóa Việt Nam ",
    avatar: "https://book365.vn/sach2.png",
    price: 350000.0,
    dimension: "22 x 35 cm",
    format: "Bìa cứng",
    totalPage: 299,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 19,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Bộ sách được biên soạn dựa trên những kết quả nghiên cứu đã được thừa nhận và công bố của ngành Văn hóa học Việt Nam từ góc nhìn địa - văn hóa. Bộ sách giới thiệu về các tiểu vùng văn hóa xứ Thanh, xứ Huế và Sài Gòn Gia Định trong tổng thể văn hóa Việt Nam, thuộc thể loại khoa học thường thức. Nội dung bao gồm các kiến thức cơ bản về lịch sử - văn hóa đặc trưng của từng tiểu vùng văn hóa, được viết bằng văn phong của các tác phẩm “văn hóa sử”, với lời văn trong sáng, dung dị. Các nội dung, thành tố văn hóa được diễn giải chi tiết, cụ thể bằng lời văn, có sử dụng tranh ảnh minh họa.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 226,
    status: false,
    createdDate: "2022-11-21T22:47:52",
    updatedDate: "2022-11-21T22:47:52",
    name: "Gương Phong Tục",
    avatar: "https://book365.vn/guong-phong-tuc.png",
    price: 560000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 220,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 22,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Gương phong tục là một cuốn sách quý chất chứa tinh hoa văn hóa dân gian được kế thừa bởi tấm lòng gìn giữ của tác giả Đoàn Duy Bình - Hàn lâm điển tịch.\nXin trích một vài đoạn trong BÀI TỰA của người biên chép để độc giả có thể hiểu thêm về giá trị của cuốn sách:\n“Thiên hạ mỗi nước có một phong tục, mà trong nước cũng mỗi nơi có một phong tục. Những nhời ca dao này tức là cái tinh thần hồn phách của thói tục trong nước hiện ra. Hễ thói tục hay thì có câu ca dao hay, thói tục dở thì có câu ca dao dở. Điều hơn nhẽ thiệt, kẻ dại người khôn, không sự gì là không đủ, cũng là một cái gương cho người trong nước ta soi chung. Không cứ nhớn nhỏ giai gái, ai cũng nên đem cái gương này mà soi vào mình; điều hay thì nghĩ xem mình có được như thế không; điều dở thì xét xem mình có phải như thế không? Hay khen, hèn chê, nào ai có bưng miệng thiên hạ được; tốt phô xấu đậy, chưa dễ mà che mắt thế gian. Nhời ông bà cổ sơ nói chẳng điều nào bỏ đi, thực là một sự khuyên răn rất thiết cho người ta, không phải là để nghêu ngao cho đỡ buồn mà thôi...”\nCuốn sách này tác giả chép nhặt công phu, từng được đăng trên Đông Dương tạp chí năm 1916 - 1917 từ số 59 đến 104. Nội dung cuôn sách được tác giả lựa lấy từng câu chia thành các mục rõ ràng, nói có sách, mách có chứng, chú thích toàn điển phương ngôn, hay thì khen, hèn thì chê, quan điểm nghị luận đầy học thức, sắc sảo",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 227,
    status: false,
    createdDate: "2022-11-21T22:47:52",
    updatedDate: "2022-11-21T22:47:52",
    name: "Huyền thoại về một vùng đất – Không gian văn hóa Tây Nguyên qua sử thi Ê-đê",
    avatar: "https://book365.vn/sach-ede.png",
    price: 200000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 400,
    language: "Tiếng Anh",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Lịch sử đã lùi xa nhưng các di sản của văn hóa Tây Nguyên vẫn còn đó. Không gian văn hóa Tây Nguyên vẫn vang ngân tiếng đàn đá, các dàn cồng chiêng vẫn hòa nhịp với âm hưởng của núi rừng, rượu cần trong các ché cổ vẫn thấm, vẫn ngấm say lòng người. Chiều sâu văn hóa của đất và người Tây Nguyên đã và đang là động lực phát triển, là nguồn động năng lớn cuốn hút những tấm lòng, trí tuệ gần xa đến với “Miền đất huyền ảo” Cao Nguyên.\nVới cách tiếp cận liên ngành và khu vực học, cuốn sách “Huyền thoại về một vùng đất – Không gian văn hóa Tây Nguyên qua sử thi Ê-đê” của GS.TS.NGƯT. Nguyễn Văn Kim tham góp một góc nhìn mới về văn hóa và con người Tây Nguyên. Trong công trình nghiên cứu này, tác giả đã đã dành nhiều trang viết đậm chất suy tư về sự huyền ảo, chất bi tráng, anh hùng, kỳ vĩ của Tây Nguyên được thể hiện và phản ánh trong sử thi Dăm Săn và các bộ sử thi của đồng bào Ê-đê.\nQua đó, một Tây Nguyên giàu tiềm năng văn hóa, kinh tế đang trỗi dậy và chắc chắn (dù còn nhiều khó khăn, thách thức) sẽ tiếp tục có những đóng góp xứng đáng với văn hóa Việt Nam, văn hóa châu Á và thế giới.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 229,
    status: false,
    createdDate: "2022-11-21T22:47:54",
    updatedDate: "2022-11-21T22:47:54",
    name: "Lịch sử và Văn hóa Việt Nam - Từ góc nhìn đổi mới",
    avatar: "https://book365.vn/sachlichsu5.png",
    price: 250000.0,
    dimension: "20 x 10 cm",
    format: "Bìa mềm",
    totalPage: 200,
    language: "Tiếng Việt",
    publicationDate: "2021-03-27T00:00:00",
    discount: 20,
    hot: false,
    act: true,
    buyCount: 0,
    desc: "Lịch sử Việt Nam từ nguyên thủy đến ngày nay có thể được coi như một chuỗi kế tiếp những hệ hình kích cỡ khác nhau, trong mỗi hệ hình lại ẩn chứa những tiểu hệ hình. Những hệ hình lịch sử chính tương đương với những thời kỳ lịch sử lớn là nguyên thủy, cổ đại, trung đại, cận đại và hiện đại. Giới học giả vẫn còn đang tranh cãi về việc phân kỳ rạch ròi các thời kỳ đó. \n\nCuốn sách xét đến 3 hệ hình chính với các thể chế chính trị tương ứng là hệ hình quân chủ quan liêu thời trung đại, hệ hình thuộc địa thực dân thời cận đại và hệ hình cộng hòa hậu thuộc địa thời hiện đại. Đó cũng là việc “hệ hình hóa” ba thực thể xã hội tương đương, bao gồm “Việt Nam truyền thống”, “Việt Nam thời thuộc Pháp” và “Việt Nam mới”. Những hệ hình lịch sử này, bên cạnh những nội dung khác biệt về bản chất, đã có một số đặc trưng chung tương đồng. Về cấu trúc, đó là các hệ hình lai ghép giữa yếu tố bản địa nội sinh với những yếu tố ngoại sinh. Trong quá trình vận hành, những hệ hình cũ và mới thường xen gối, chồng lấn lên nhau, tạo nên những thời đoạn đan xen giao thời quá độ. Tuy nhiên, ở những thời đoạn thịnh đạt, hệ hình đã hỗn dung tích hợp được một cách khá nhuần nhuyễn những yếu tố khác lạ, tương phản nhau, tạo thành một bản sắc riêng biệt của cộng đồng mang tính dân tộc.",
    slug: null,
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 0,
  },
  {
    id: 165,
    status: true,
    createdDate: "2021-05-12T11:41:47",
    updatedDate: "2021-05-12T11:42:18",
    name: "Mbappe - Cậu bé vàng",
    avatar: "https://cf.shopee.vn/file/f13213596aaaadc46f488e09a2f67a81",
    price: 250000.0,
    dimension: "22 x 35 cm",
    format: "Bìa mềm",
    totalPage: 290,
    language: "Tiếng Việt",
    publicationDate: "2021-05-12T00:00:00",
    discount: 10,
    hot: true,
    act: true,
    buyCount: 0,
    desc: "Những điều diệu kỳ từ tư tưởng và triết lý sống Khổng Tử Tác giả Yu Dan là người Bắc Kinh, thạc sĩ văn học cổ điển Trung Quốc, tiến sĩ ngành điện ảnh-truyền hình.\r\n",
    slug: "mbappe-cau-be-vang-1620794537850",
    file: null,
    files: null,
    starAvg: 0,
    numberOfSearchBook: 13,
  },
];
